// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sekizui/v1/command.proto

package sekizuiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED      Status = 0
	Status_STATUS_OK               Status = 1
	Status_STATUS_DENIED           Status = 2 // policy refused
	Status_STATUS_ESCALATED        Status = 3 // awaiting human approval
	Status_STATUS_RATE_LIMITED     Status = 4 // quota or fairness limit
	Status_STATUS_TARGET_ERROR     Status = 5 // the external system failed
	Status_STATUS_WOULD_HAVE_FIRED Status = 6 // dry_run only
	// The request was well-formed enough to reach the enforcement path and wrong
	// enough to refuse: `restore_target` on a target nobody withdrew (D133),
	// `fire_anzen` naming something that is not a rule (D134).
	//
	// ADDED BECAUSE THESE REFUSALS HAD NO STATUS AT ALL. `fault.KindInvalidArgument`
	// is Deliberate, so D135 turned both into results — and `Kind.Status()` had no
	// case for it, so both arrived as STATUS_UNSPECIFIED. The zero value means
	// "nobody set this", which is the one thing a deliberate refusal must never
	// say. It survived because the test that covers it asserted `!= STATUS_OK`,
	// and UNSPECIFIED satisfies that.
	//
	// NOT collapsed into DENIED: a denial is a grant to review and this is a
	// request to correct, and §7.1's whole argument is that an operator should not
	// have to infer which.
	Status_STATUS_INVALID_ARGUMENT Status = 7
	// The deployment cannot perform this command as configured (D201).
	//
	// **ADDED FOR THE SAME REASON STATUS_INVALID_ARGUMENT WAS**: `KindConfig` is
	// now a deliberate refusal, so D135 makes it a RESULT — and with no case in
	// `Kind.Status()` it would have reached callers as STATUS_UNSPECIFIED, the
	// zero value meaning "nobody set this". D138 argues against mirroring the
	// taxonomy into this enum, and this is not that: none of the existing members
	// is honest here. DENIED says a policy refused, TARGET_ERROR says the far side
	// failed — the misattribution D200 exists to remove — and INVALID_ARGUMENT
	// points at the caller's arguments, which are fine.
	//
	// The coarse answer a caller branches on is "this cannot succeed until a
	// human changes something here", which no other member carries.
	Status_STATUS_MISCONFIGURED Status = 8
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_DENIED",
		3: "STATUS_ESCALATED",
		4: "STATUS_RATE_LIMITED",
		5: "STATUS_TARGET_ERROR",
		6: "STATUS_WOULD_HAVE_FIRED",
		7: "STATUS_INVALID_ARGUMENT",
		8: "STATUS_MISCONFIGURED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":      0,
		"STATUS_OK":               1,
		"STATUS_DENIED":           2,
		"STATUS_ESCALATED":        3,
		"STATUS_RATE_LIMITED":     4,
		"STATUS_TARGET_ERROR":     5,
		"STATUS_WOULD_HAVE_FIRED": 6,
		"STATUS_INVALID_ARGUMENT": 7,
		"STATUS_MISCONFIGURED":    8,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_command_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_sekizui_v1_command_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_command_proto_rawDescGZIP(), []int{0}
}

// Command is a request to act on an external system.
//
// CRITICAL — `target_ref` is a STRING, not a resolved Target message.
//
// Callers name a target; they never construct one. Resolution (ref -> credentials
// -> tenant -> region) happens inside Sekizui, gated by the caller's grants.
// If Target were a wire message that callers populated, two guarantees would be
// lost at once:
//  1. agents would be able to influence credential selection (§9.5 — rejected)
//  2. §6's "tenant absence is a compile error" would be unenforceable, because
//     the resolver would no longer be the sole constructor
//
// This is the single most important shape decision in this file.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "jira.create_issue". Must appear in the effective capability set.
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// e.g. "jira:acme". Resolved internally — see the note above.
	TargetRef string `protobuf:"bytes,2,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	// Action arguments. Validated against the action's registered input schema,
	// same mechanism as envelope payloads (D40).
	Args *structpb.Struct `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	// Client-supplied idempotency key. REQUIRED for mutating actions.
	//
	// Agents retry with LLM-driven, undisciplined logic; without this a timeout
	// becomes two Jira tickets. Matters more here than in a service with
	// hand-written callers (§7.1).
	IdempotencyKey string `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Set when this command was produced by a reflex rather than requested
	// directly, so the resulting Decision can record what triggered it (§4.11.1).
	Causation *Causation `protobuf:"bytes,5,opt,name=causation,proto3" json:"causation,omitempty"`
	// Evaluate and audit, but do not perform the side effect.
	//
	// Shadow mode for reflexes (§4.11.4 item 3) uses this; it is exposed on the
	// wire so callers can dry-run too. Produces a Decision with
	// VERDICT_WOULD_HAVE_FIRED.
	DryRun bool `protobuf:"varint,6,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	// Trace is the span context this command belongs to, for the INTERNAL
	// propagation path (D216).
	//
	// **EXISTS FOR THE SAME REASON `causation` DOES, one field up: a command
	// produced by a reflex was not requested over the wire, so there is no
	// inbound `traceparent` header to read it from.** Without this a
	// reflex-originated decision would lose the trace of the envelope that
	// triggered it, and the causal chain a trace exists to show would break at
	// exactly the interesting hop.
	//
	// **THE HEADER IS AUTHORITATIVE WHEN PRESENT.** For a wire caller this field
	// is ignored, so the body can never override the header — not because the
	// trace is trusted (it is not; nothing authorises on it, CONTRACTS 89) but
	// because two sources for one value with no stated precedence is how they
	// come to disagree silently.
	Trace         *Trace `protobuf:"bytes,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_sekizui_v1_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Command) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *Command) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Command) GetCausation() *Causation {
	if x != nil {
		return x.Causation
	}
	return nil
}

func (x *Command) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *Command) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

// CommandResult is the outcome of a single command.
//
// One command performs exactly ONE action (D31). Multiple actions are multiple
// commands — deliberately avoiding partial-failure semantics inside one request,
// where there is no good answer for what the overall outcome was.
type CommandResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The audit Decision this produced. Always populated, including on denial —
	// denials are the highest-value audit rows (§5.4).
	DecisionId string `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Status     Status `protobuf:"varint,2,opt,name=status,proto3,enum=sekizui.v1.Status" json:"status,omitempty"`
	// Action output, e.g. {"issue_key": "PROJ-123", "url": "..."}.
	// Empty on denial or dry_run.
	Result *structpb.Struct `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	// Populated when status is DENIED or ESCALATED. Names the matched rule so the
	// caller (or agent) learns *why*, not just that it failed.
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// True when this response was served from the idempotency cache rather than by
	// performing the action again.
	Deduplicated bool `protobuf:"varint,5,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	// The stable taxonomy name for a DELIBERATE refusal: "denied", "residency",
	// "rate_limited", "escalated", "spec_drift", "budget_exceeded",
	// "invalid_argument". Empty when the command was not deliberately refused.
	//
	// WHY, WHEN `status` EXISTS. `status` is deliberately coarser: denied,
	// unauthenticated and residency all map to STATUS_DENIED, because a caller
	// mostly needs "refused" versus "the far side broke". Since D135 turned every
	// deliberate refusal into a result rather than an error, that collapse is the
	// ONLY thing a caller sees — the finer answer survived on the record and in
	// the metric, and reached nobody.
	//
	// That matters most IN-PROCESS. The reflex engine calls Enforce directly
	// (D18, D69) and receives a CommandResult, not an error, so it cannot ask
	// fault.KindOf. From P5 it has to decide whether to retry, and the question
	// it is really asking is RETRYABILITY — which `refused_by` cannot answer,
	// because REFUSED_BY_ANZEN spans a forbid rule (never retry) and a
	// concurrency cap (retry with backoff). Those differ in exactly the way the
	// caller cares about.
	//
	// A STRING, NOT AN ENUM, matching `Envelope.stage` (CONTRACTS §3.3). The
	// taxonomy is fault.Kind, which has eighteen members and grows with the
	// system; mirroring it into a proto enum creates a second vocabulary to keep
	// in step, and a divergence between them would be silent. This is the same
	// word the metric label and the audit record already use, so a dashboard, a
	// log line and this field read alike.
	//
	// ADDITIVE: `status` is unchanged, so no existing client is affected.
	Kind string `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	// The SEIREN (精錬) beside `result`, as on QueryResponse (D300, D317): what
	// the `refines:` rules imposed on this caller made of the action's output.
	// Absent when no rule is imposed; `result` stays silver.
	Seiren        *Seiren `protobuf:"bytes,7,opt,name=seiren,proto3" json:"seiren,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_sekizui_v1_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandResult) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *CommandResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *CommandResult) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CommandResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CommandResult) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

func (x *CommandResult) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CommandResult) GetSeiren() *Seiren {
	if x != nil {
		return x.Seiren
	}
	return nil
}

var File_sekizui_v1_command_proto protoreflect.FileDescriptor

const file_sekizui_v1_command_proto_rawDesc = "" +
	"\n" +
	"\x18sekizui/v1/command.proto\x12\n" +
	"sekizui.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19sekizui/v1/envelope.proto\x1a\x19sekizui/v1/decision.proto\x1a\x17sekizui/v1/seiren.proto\"\x8d\x02\n" +
	"\aCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x02 \x01(\tR\ttargetRef\x12+\n" +
	"\x04args\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04args\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x123\n" +
	"\tcausation\x18\x05 \x01(\v2\x15.sekizui.v1.CausationR\tcausation\x12\x17\n" +
	"\adry_run\x18\x06 \x01(\bR\x06dryRun\x12'\n" +
	"\x05trace\x18\a \x01(\v2\x11.sekizui.v1.TraceR\x05trace\"\x89\x02\n" +
	"\rCommandResult\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.sekizui.v1.StatusR\x06status\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\"\n" +
	"\fdeduplicated\x18\x05 \x01(\bR\fdeduplicated\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\tR\x04kind\x12*\n" +
	"\x06seiren\x18\a \x01(\v2\x12.sekizui.v1.SeirenR\x06seiren*\xde\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x11\n" +
	"\rSTATUS_DENIED\x10\x02\x12\x14\n" +
	"\x10STATUS_ESCALATED\x10\x03\x12\x17\n" +
	"\x13STATUS_RATE_LIMITED\x10\x04\x12\x17\n" +
	"\x13STATUS_TARGET_ERROR\x10\x05\x12\x1b\n" +
	"\x17STATUS_WOULD_HAVE_FIRED\x10\x06\x12\x1b\n" +
	"\x17STATUS_INVALID_ARGUMENT\x10\a\x12\x18\n" +
	"\x14STATUS_MISCONFIGURED\x10\bB\xa8\x01\n" +
	"\x0ecom.sekizui.v1B\fCommandProtoP\x01Z?github.com/fullstorydev/sekizui/pkg/schema/sekizui/v1;sekizuiv1\xa2\x02\x03SXX\xaa\x02\n" +
	"Sekizui.V1\xca\x02\n" +
	"Sekizui\\V1\xe2\x02\x16Sekizui\\V1\\GPBMetadata\xea\x02\vSekizui::V1b\x06proto3"

var (
	file_sekizui_v1_command_proto_rawDescOnce sync.Once
	file_sekizui_v1_command_proto_rawDescData []byte
)

func file_sekizui_v1_command_proto_rawDescGZIP() []byte {
	file_sekizui_v1_command_proto_rawDescOnce.Do(func() {
		file_sekizui_v1_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sekizui_v1_command_proto_rawDesc), len(file_sekizui_v1_command_proto_rawDesc)))
	})
	return file_sekizui_v1_command_proto_rawDescData
}

var file_sekizui_v1_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sekizui_v1_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sekizui_v1_command_proto_goTypes = []any{
	(Status)(0),             // 0: sekizui.v1.Status
	(*Command)(nil),         // 1: sekizui.v1.Command
	(*CommandResult)(nil),   // 2: sekizui.v1.CommandResult
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
	(*Causation)(nil),       // 4: sekizui.v1.Causation
	(*Trace)(nil),           // 5: sekizui.v1.Trace
	(*Seiren)(nil),          // 6: sekizui.v1.Seiren
}
var file_sekizui_v1_command_proto_depIdxs = []int32{
	3, // 0: sekizui.v1.Command.args:type_name -> google.protobuf.Struct
	4, // 1: sekizui.v1.Command.causation:type_name -> sekizui.v1.Causation
	5, // 2: sekizui.v1.Command.trace:type_name -> sekizui.v1.Trace
	0, // 3: sekizui.v1.CommandResult.status:type_name -> sekizui.v1.Status
	3, // 4: sekizui.v1.CommandResult.result:type_name -> google.protobuf.Struct
	6, // 5: sekizui.v1.CommandResult.seiren:type_name -> sekizui.v1.Seiren
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sekizui_v1_command_proto_init() }
func file_sekizui_v1_command_proto_init() {
	if File_sekizui_v1_command_proto != nil {
		return
	}
	file_sekizui_v1_envelope_proto_init()
	file_sekizui_v1_decision_proto_init()
	file_sekizui_v1_seiren_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sekizui_v1_command_proto_rawDesc), len(file_sekizui_v1_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sekizui_v1_command_proto_goTypes,
		DependencyIndexes: file_sekizui_v1_command_proto_depIdxs,
		EnumInfos:         file_sekizui_v1_command_proto_enumTypes,
		MessageInfos:      file_sekizui_v1_command_proto_msgTypes,
	}.Build()
	File_sekizui_v1_command_proto = out.File
	file_sekizui_v1_command_proto_goTypes = nil
	file_sekizui_v1_command_proto_depIdxs = nil
}
