// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sekizui/v1/core.proto

package sekizuiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthMethod int32

const (
	AuthMethod_AUTH_METHOD_UNSPECIFIED AuthMethod = 0
	AuthMethod_AUTH_METHOD_MTLS        AuthMethod = 1 // workload identity (SPIFFE or platform equivalent)
	AuthMethod_AUTH_METHOD_TOKEN       AuthMethod = 2 // signed bearer token
	// In-process, with no authentication performed because none is possible.
	//
	// A reflex has no certificate and no token: it IS Sekizui, constructing an
	// identity for a rule an operator configured. UNSPECIFIED would be wrong —
	// that is the zero value meaning "nobody set this", and an audit row cannot
	// then distinguish a deliberate internal action from a field somebody forgot
	// to populate. Those are different facts and a reviewer needs both.
	AuthMethod_AUTH_METHOD_INTERNAL AuthMethod = 3
)

// Enum value maps for AuthMethod.
var (
	AuthMethod_name = map[int32]string{
		0: "AUTH_METHOD_UNSPECIFIED",
		1: "AUTH_METHOD_MTLS",
		2: "AUTH_METHOD_TOKEN",
		3: "AUTH_METHOD_INTERNAL",
	}
	AuthMethod_value = map[string]int32{
		"AUTH_METHOD_UNSPECIFIED": 0,
		"AUTH_METHOD_MTLS":        1,
		"AUTH_METHOD_TOKEN":       2,
		"AUTH_METHOD_INTERNAL":    3,
	}
)

func (x AuthMethod) Enum() *AuthMethod {
	p := new(AuthMethod)
	*p = x
	return p
}

func (x AuthMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_core_proto_enumTypes[0].Descriptor()
}

func (AuthMethod) Type() protoreflect.EnumType {
	return &file_sekizui_v1_core_proto_enumTypes[0]
}

func (x AuthMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthMethod.Descriptor instead.
func (AuthMethod) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{0}
}

type Assertion int32

const (
	Assertion_ASSERTION_UNSPECIFIED Assertion = 0
	Assertion_ASSERTION_ASSERTED    Assertion = 1
	Assertion_ASSERTION_SIGNED      Assertion = 2
)

// Enum value maps for Assertion.
var (
	Assertion_name = map[int32]string{
		0: "ASSERTION_UNSPECIFIED",
		1: "ASSERTION_ASSERTED",
		2: "ASSERTION_SIGNED",
	}
	Assertion_value = map[string]int32{
		"ASSERTION_UNSPECIFIED": 0,
		"ASSERTION_ASSERTED":    1,
		"ASSERTION_SIGNED":      2,
	}
)

func (x Assertion) Enum() *Assertion {
	p := new(Assertion)
	*p = x
	return p
}

func (x Assertion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Assertion) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_core_proto_enumTypes[1].Descriptor()
}

func (Assertion) Type() protoreflect.EnumType {
	return &file_sekizui_v1_core_proto_enumTypes[1]
}

func (x Assertion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Assertion.Descriptor instead.
func (Assertion) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{1}
}

type Disposition int32

const (
	Disposition_DISPOSITION_UNSPECIFIED Disposition = 0
	Disposition_DISPOSITION_ALLOW       Disposition = 1
	Disposition_DISPOSITION_ESCALATE    Disposition = 2
)

// Enum value maps for Disposition.
var (
	Disposition_name = map[int32]string{
		0: "DISPOSITION_UNSPECIFIED",
		1: "DISPOSITION_ALLOW",
		2: "DISPOSITION_ESCALATE",
	}
	Disposition_value = map[string]int32{
		"DISPOSITION_UNSPECIFIED": 0,
		"DISPOSITION_ALLOW":       1,
		"DISPOSITION_ESCALATE":    2,
	}
)

func (x Disposition) Enum() *Disposition {
	p := new(Disposition)
	*p = x
	return p
}

func (x Disposition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Disposition) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_core_proto_enumTypes[2].Descriptor()
}

func (Disposition) Type() protoreflect.EnumType {
	return &file_sekizui_v1_core_proto_enumTypes[2]
}

func (x Disposition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Disposition.Descriptor instead.
func (Disposition) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{2}
}

// Identity is the full authorisation context of a request.
//
// Three separate things, deliberately not collapsed (§4.4):
//
//	caller  — PROVEN. Who is on the wire.
//	subject — ASSERTED. Who the action is on behalf of. Must be authorised.
//	chain   — the delegation path, recorded for audit.
//
// Standalone deployments are the degenerate case: caller == subject and the
// chain has length 1 (D6). There is no separate mode.
//
// There is deliberately NO operator/customer field. One deployment == one
// operator's world (D37); customer isolation belongs to whatever embeds Sekizui.
type Identity struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Caller  *Caller                `protobuf:"bytes,1,opt,name=caller,proto3" json:"caller,omitempty"`
	Subject *Subject               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Full delegation path, outermost first. e.g. ["mesh:primary", "agent:triage"].
	// Recorded in every Decision (D39) — "who authorised this", as distinct from
	// Causation, which records "what triggered this".
	Chain []string `protobuf:"bytes,3,rep,name=chain,proto3" json:"chain,omitempty"`
	// Correlates this request across traces, envelopes, and decision records.
	TraceId       string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_sekizui_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *Identity) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Identity) GetChain() []string {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *Identity) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// Caller is the cryptographically proven identity on the wire.
type Caller struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "mesh:primary", "agent:triage", "user:alice", "reflex:checkout-friction".
	// Reflexes are principals like any other — no bypass (D18).
	Principal string     `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Method    AuthMethod `protobuf:"varint,2,opt,name=method,proto3,enum=sekizui.v1.AuthMethod" json:"method,omitempty"`
	// Certificate fingerprint or token subject. Recorded for audit; never a secret.
	CredentialId  string `protobuf:"bytes,3,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Caller) Reset() {
	*x = Caller{}
	mi := &file_sekizui_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Caller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Caller) ProtoMessage() {}

func (x *Caller) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Caller.ProtoReflect.Descriptor instead.
func (*Caller) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *Caller) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Caller) GetMethod() AuthMethod {
	if x != nil {
		return x.Method
	}
	return AuthMethod_AUTH_METHOD_UNSPECIFIED
}

func (x *Caller) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

// Subject is the principal an action is performed on behalf of.
//
// ASSERTED means the caller claims it and Sekizui checks `may_speak_for`
// (§4.4.2 tier 1). SIGNED means an identity provider the caller does not
// control vouched for it (tier 2) — the caller cannot forge it.
//
// Same wire shape for both tiers, so tier 2 is a verification upgrade rather
// than a schema migration.
type Subject struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Principal string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Assertion Assertion              `protobuf:"varint,2,opt,name=assertion,proto3,enum=sekizui.v1.Assertion" json:"assertion,omitempty"`
	// Present only when assertion == ASSERTION_SIGNED: the SHA-256 of the token,
	// so a record joins to a token without holding one (D318) — the token itself
	// is a bearer credential and is never recorded.
	Proof []byte `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	// SIGNED ONLY (D303, D318), each additive so tier two stays a verification
	// upgrade rather than a schema migration (§4.4.2):
	//
	// the pinned issuer that signed the token;
	Issuer string `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// the `role:` principal whose grants the token's role selected — the record
	// names the individual in `principal` and the grant set here;
	Role string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	// true when the token carried no certificate binding and its issuer allowed
	// that (`require_bound: false`) — relaxed by a visible act, and visible here;
	Unbound bool `protobuf:"varint,6,opt,name=unbound,proto3" json:"unbound,omitempty"`
	// the token's narrowing: grants it listed (which may only intersect with the
	// role's) and lenses it listed (which may only add);
	TokenGrants []string `protobuf:"bytes,7,rep,name=token_grants,json=tokenGrants,proto3" json:"token_grants,omitempty"`
	TokenLenses []string `protobuf:"bytes,8,rep,name=token_lenses,json=tokenLenses,proto3" json:"token_lenses,omitempty"`
	// grants the token claimed that its role does not hold — refused, and noted,
	// because a token claiming more than its role is either a broker bug or a
	// forgery testing the edge (D303).
	ExcessGrants  []string `protobuf:"bytes,9,rep,name=excess_grants,json=excessGrants,proto3" json:"excess_grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_sekizui_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *Subject) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Subject) GetAssertion() Assertion {
	if x != nil {
		return x.Assertion
	}
	return Assertion_ASSERTION_UNSPECIFIED
}

func (x *Subject) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *Subject) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Subject) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Subject) GetUnbound() bool {
	if x != nil {
		return x.Unbound
	}
	return false
}

func (x *Subject) GetTokenGrants() []string {
	if x != nil {
		return x.TokenGrants
	}
	return nil
}

func (x *Subject) GetTokenLenses() []string {
	if x != nil {
		return x.TokenLenses
	}
	return nil
}

func (x *Subject) GetExcessGrants() []string {
	if x != nil {
		return x.ExcessGrants
	}
	return nil
}

// Capability is one granted (action x target x constraints) triple.
//
// Effective permission for a request is the INTERSECTION of the caller's and
// the subject's capabilities (D7) — closing escalation in both directions.
type Capability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "jira.create_issue", "bigquery.query", "kafka.publish".
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// Target *reference*, not a resolved target. See Command.target_ref.
	TargetRef string `protobuf:"bytes,2,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	// Field constraints, e.g. {"project": {in: ["PROJ"]}}.
	Where  map[string]*Constraint `protobuf:"bytes,3,rep,name=where,proto3" json:"where,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limits *Limits                `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	// Human/LLM-readable, WITH CONSTRAINTS INLINED (§4.9 property 2):
	//
	//	"Comment on an issue in Jira instance acme. Only project PROJ permitted."
	//
	// Generated, never hand-written, so it cannot drift from what is enforceable.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// ALLOW or ESCALATE (human approval required).
	Disposition Disposition `protobuf:"varint,6,opt,name=disposition,proto3,enum=sekizui.v1.Disposition" json:"disposition,omitempty"`
	// For an MCP tool whose target shares an upstream budget with native
	// targets, the reviewer's declared relation (D323): the native actions it
	// mirrors, or "none" (it reaches what only it reaches), or "opaque" (nobody
	// could bound what it reaches). Empty for every other capability. Grant
	// review reads the doors onto one upstream together through this.
	Native        []string `protobuf:"bytes,7,rep,name=native,proto3" json:"native,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_sekizui_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *Capability) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Capability) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *Capability) GetWhere() map[string]*Constraint {
	if x != nil {
		return x.Where
	}
	return nil
}

func (x *Capability) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Capability) GetDisposition() Disposition {
	if x != nil {
		return x.Disposition
	}
	return Disposition_DISPOSITION_UNSPECIFIED
}

func (x *Capability) GetNative() []string {
	if x != nil {
		return x.Native
	}
	return nil
}

type Constraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	In            []string               `protobuf:"bytes,1,rep,name=in,proto3" json:"in,omitempty"`
	NotIn         []string               `protobuf:"bytes,2,rep,name=not_in,json=notIn,proto3" json:"not_in,omitempty"`
	Matches       string                 `protobuf:"bytes,3,opt,name=matches,proto3" json:"matches,omitempty"` // regex
	Contains      string                 `protobuf:"bytes,4,opt,name=contains,proto3" json:"contains,omitempty"`
	Gte           float64                `protobuf:"fixed64,5,opt,name=gte,proto3" json:"gte,omitempty"`
	Lte           float64                `protobuf:"fixed64,6,opt,name=lte,proto3" json:"lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_sekizui_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *Constraint) GetIn() []string {
	if x != nil {
		return x.In
	}
	return nil
}

func (x *Constraint) GetNotIn() []string {
	if x != nil {
		return x.NotIn
	}
	return nil
}

func (x *Constraint) GetMatches() string {
	if x != nil {
		return x.Matches
	}
	return ""
}

func (x *Constraint) GetContains() string {
	if x != nil {
		return x.Contains
	}
	return ""
}

func (x *Constraint) GetGte() float64 {
	if x != nil {
		return x.Gte
	}
	return 0
}

func (x *Constraint) GetLte() float64 {
	if x != nil {
		return x.Lte
	}
	return 0
}

type Limits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatePerHour   uint32                 `protobuf:"varint,1,opt,name=rate_per_hour,json=ratePerHour,proto3" json:"rate_per_hour,omitempty"`
	MaxBytes      uint64                 `protobuf:"varint,2,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	MaxResults    uint32                 `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_sekizui_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *Limits) GetRatePerHour() uint32 {
	if x != nil {
		return x.RatePerHour
	}
	return 0
}

func (x *Limits) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *Limits) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

var File_sekizui_v1_core_proto protoreflect.FileDescriptor

const file_sekizui_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x15sekizui/v1/core.proto\x12\n" +
	"sekizui.v1\"\x96\x01\n" +
	"\bIdentity\x12*\n" +
	"\x06caller\x18\x01 \x01(\v2\x12.sekizui.v1.CallerR\x06caller\x12-\n" +
	"\asubject\x18\x02 \x01(\v2\x13.sekizui.v1.SubjectR\asubject\x12\x14\n" +
	"\x05chain\x18\x03 \x03(\tR\x05chain\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"{\n" +
	"\x06Caller\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12.\n" +
	"\x06method\x18\x02 \x01(\x0e2\x16.sekizui.v1.AuthMethodR\x06method\x12#\n" +
	"\rcredential_id\x18\x03 \x01(\tR\fcredentialId\"\xa3\x02\n" +
	"\aSubject\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x123\n" +
	"\tassertion\x18\x02 \x01(\x0e2\x15.sekizui.v1.AssertionR\tassertion\x12\x14\n" +
	"\x05proof\x18\x03 \x01(\fR\x05proof\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x18\n" +
	"\aunbound\x18\x06 \x01(\bR\aunbound\x12!\n" +
	"\ftoken_grants\x18\a \x03(\tR\vtokenGrants\x12!\n" +
	"\ftoken_lenses\x18\b \x03(\tR\vtokenLenses\x12#\n" +
	"\rexcess_grants\x18\t \x03(\tR\fexcessGrants\"\xef\x02\n" +
	"\n" +
	"Capability\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x02 \x01(\tR\ttargetRef\x127\n" +
	"\x05where\x18\x03 \x03(\v2!.sekizui.v1.Capability.WhereEntryR\x05where\x12*\n" +
	"\x06limits\x18\x04 \x01(\v2\x12.sekizui.v1.LimitsR\x06limits\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x129\n" +
	"\vdisposition\x18\x06 \x01(\x0e2\x17.sekizui.v1.DispositionR\vdisposition\x12\x16\n" +
	"\x06native\x18\a \x03(\tR\x06native\x1aP\n" +
	"\n" +
	"WhereEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.sekizui.v1.ConstraintR\x05value:\x028\x01\"\x8d\x01\n" +
	"\n" +
	"Constraint\x12\x0e\n" +
	"\x02in\x18\x01 \x03(\tR\x02in\x12\x15\n" +
	"\x06not_in\x18\x02 \x03(\tR\x05notIn\x12\x18\n" +
	"\amatches\x18\x03 \x01(\tR\amatches\x12\x1a\n" +
	"\bcontains\x18\x04 \x01(\tR\bcontains\x12\x10\n" +
	"\x03gte\x18\x05 \x01(\x01R\x03gte\x12\x10\n" +
	"\x03lte\x18\x06 \x01(\x01R\x03lte\"j\n" +
	"\x06Limits\x12\"\n" +
	"\rrate_per_hour\x18\x01 \x01(\rR\vratePerHour\x12\x1b\n" +
	"\tmax_bytes\x18\x02 \x01(\x04R\bmaxBytes\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\rR\n" +
	"maxResults*p\n" +
	"\n" +
	"AuthMethod\x12\x1b\n" +
	"\x17AUTH_METHOD_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AUTH_METHOD_MTLS\x10\x01\x12\x15\n" +
	"\x11AUTH_METHOD_TOKEN\x10\x02\x12\x18\n" +
	"\x14AUTH_METHOD_INTERNAL\x10\x03*T\n" +
	"\tAssertion\x12\x19\n" +
	"\x15ASSERTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ASSERTION_ASSERTED\x10\x01\x12\x14\n" +
	"\x10ASSERTION_SIGNED\x10\x02*[\n" +
	"\vDisposition\x12\x1b\n" +
	"\x17DISPOSITION_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11DISPOSITION_ALLOW\x10\x01\x12\x18\n" +
	"\x14DISPOSITION_ESCALATE\x10\x02B\xa5\x01\n" +
	"\x0ecom.sekizui.v1B\tCoreProtoP\x01Z?github.com/fullstorydev/sekizui/pkg/schema/sekizui/v1;sekizuiv1\xa2\x02\x03SXX\xaa\x02\n" +
	"Sekizui.V1\xca\x02\n" +
	"Sekizui\\V1\xe2\x02\x16Sekizui\\V1\\GPBMetadata\xea\x02\vSekizui::V1b\x06proto3"

var (
	file_sekizui_v1_core_proto_rawDescOnce sync.Once
	file_sekizui_v1_core_proto_rawDescData []byte
)

func file_sekizui_v1_core_proto_rawDescGZIP() []byte {
	file_sekizui_v1_core_proto_rawDescOnce.Do(func() {
		file_sekizui_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sekizui_v1_core_proto_rawDesc), len(file_sekizui_v1_core_proto_rawDesc)))
	})
	return file_sekizui_v1_core_proto_rawDescData
}

var file_sekizui_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sekizui_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sekizui_v1_core_proto_goTypes = []any{
	(AuthMethod)(0),    // 0: sekizui.v1.AuthMethod
	(Assertion)(0),     // 1: sekizui.v1.Assertion
	(Disposition)(0),   // 2: sekizui.v1.Disposition
	(*Identity)(nil),   // 3: sekizui.v1.Identity
	(*Caller)(nil),     // 4: sekizui.v1.Caller
	(*Subject)(nil),    // 5: sekizui.v1.Subject
	(*Capability)(nil), // 6: sekizui.v1.Capability
	(*Constraint)(nil), // 7: sekizui.v1.Constraint
	(*Limits)(nil),     // 8: sekizui.v1.Limits
	nil,                // 9: sekizui.v1.Capability.WhereEntry
}
var file_sekizui_v1_core_proto_depIdxs = []int32{
	4, // 0: sekizui.v1.Identity.caller:type_name -> sekizui.v1.Caller
	5, // 1: sekizui.v1.Identity.subject:type_name -> sekizui.v1.Subject
	0, // 2: sekizui.v1.Caller.method:type_name -> sekizui.v1.AuthMethod
	1, // 3: sekizui.v1.Subject.assertion:type_name -> sekizui.v1.Assertion
	9, // 4: sekizui.v1.Capability.where:type_name -> sekizui.v1.Capability.WhereEntry
	8, // 5: sekizui.v1.Capability.limits:type_name -> sekizui.v1.Limits
	2, // 6: sekizui.v1.Capability.disposition:type_name -> sekizui.v1.Disposition
	7, // 7: sekizui.v1.Capability.WhereEntry.value:type_name -> sekizui.v1.Constraint
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_sekizui_v1_core_proto_init() }
func file_sekizui_v1_core_proto_init() {
	if File_sekizui_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sekizui_v1_core_proto_rawDesc), len(file_sekizui_v1_core_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sekizui_v1_core_proto_goTypes,
		DependencyIndexes: file_sekizui_v1_core_proto_depIdxs,
		EnumInfos:         file_sekizui_v1_core_proto_enumTypes,
		MessageInfos:      file_sekizui_v1_core_proto_msgTypes,
	}.Build()
	File_sekizui_v1_core_proto = out.File
	file_sekizui_v1_core_proto_goTypes = nil
	file_sekizui_v1_core_proto_depIdxs = nil
}
