// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sekizui/v1/decision.proto

package sekizuiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RefusedBy names the stage of the enforcement path that refused a command.
//
// WHY A FIELD AND NOT JUST THE KIND. `fault.Kind` used to answer this by
// implication — a revocation had its own kind — until that was collapsed into
// KindDenied, which was right for the taxonomy (a revocation IS a denial, and
// 18 kinds to say so is a poor trade) and left the record unable to tell a
// policy denial from a credential revocation. This puts the distinction back at
// the layer that should have carried it: the record a human reads, rather than
// the enum a driver switches on.
//
// AN ENUM RATHER THAN A STRING, unlike `Revocation.severity` above, and the
// difference is deliberate. That field mirrors anzen's vocabulary, which is
// configuration and may grow without touching this schema. These are the stages
// of the enforcement path — there is exactly one of it (D18) — so a new value
// means the path itself changed, which should be a deliberate schema edit and
// not a new string appearing in a warehouse.
type RefusedBy int32

const (
	RefusedBy_REFUSED_BY_UNSPECIFIED RefusedBy = 0
	// An anzen guard: a ceiling no grant can exceed (D71). Checked before policy,
	// which is what makes it a ceiling rather than an opinion.
	RefusedBy_REFUSED_BY_ANZEN RefusedBy = 1
	// Policy: the principal had no grant covering this action and target.
	RefusedBy_REFUSED_BY_POLICY RefusedBy = 2
	// Residency: the target's region conflicts with the instance's (D29 item 2).
	// Separate from policy because the remedy is completely different — a denial
	// is a grant to review, a residency conflict is a deployment topology
	// problem, and §7.1 item 2 treats it as a guarantee rather than a rule.
	RefusedBy_REFUSED_BY_RESIDENCY RefusedBy = 3
	// Break-glass: the target was withdrawn by `revoke_credential` or
	// `quarantine_target` (§4.7.10, D106).
	RefusedBy_REFUSED_BY_WITHDRAWAL RefusedBy = 4
	// Credential: the credential could not be USED, and Sekizui decided not to
	// proceed — D152's monotonic guard refusing a version that moved backwards
	// being the case that forced this member (D201).
	//
	// **ADDED BECAUSE A REAL REFUSAL WAS BEING RECORDED AS RESIDENCY.** The
	// resolve stage labelled every deliberate refusal `REFUSED_BY_RESIDENCY`,
	// gating on `Deliberate()` as a stand-in for "is this residency" — so a
	// credential downgrade, which is exactly what a disabled compromised version
	// looks like, produced an audit row naming data residency as the reason. The
	// control fired correctly and the record explained it wrongly, which is worse
	// than either alone.
	RefusedBy_REFUSED_BY_CREDENTIAL RefusedBy = 5
	// Configuration: this deployment cannot perform the command as configured —
	// a target whose base_url is not usable, a vetted spec that is absent (D201).
	//
	// A stage in the sense that matters here: the command was refused BEFORE the
	// call, deliberately, by Sekizui rather than by a policy or a ceiling. The
	// remedy is a config edit and a redeploy, which is why it must not read as a
	// denial — an operator reviewing denials would find a grant to argue about
	// and no grant is involved.
	RefusedBy_REFUSED_BY_CONFIGURATION RefusedBy = 6
	// Request: the CALLER malformed the command, and it was refused before any
	// ceiling was consulted (D215).
	//
	// **THE FIRST STAGE, AND IT HAD NO MEMBER.** An oversized idempotency key or
	// an unusable trace id is refused ahead of suspension, residency, anzen and
	// policy — there is nothing to consult, because the request itself cannot be
	// recorded safely. Without this member such a refusal shipped
	// `REFUSED_BY_UNSPECIFIED`, which is the zero value meaning "nobody set
	// this": exactly the defect D201 spent an entry on, where a credential
	// downgrade was recorded as a residency refusal because the stage could not
	// say otherwise.
	//
	// ADDED WITH ITS WRITER, which is the rule the note below states. It is set
	// by `enforceOnce`'s request validation, and the value is deliberately
	// distinct from CONFIGURATION: the remedy there is a config edit by an
	// operator, and here it is a corrected request by the caller (D200's
	// attribution axis, applied to a stage).
	RefusedBy_REFUSED_BY_REQUEST RefusedBy = 7
	// THE METER: §4.3.4's consuming controls — the shared rate budget (D143) and
	// the circuit breaker (D141). The target has capacity or it does not, and
	// neither answer is about the caller's grant.
	//
	// **A NEW VALUE BECAUSE THE PATH BECAME EXPLICIT, WHICH IS WHAT THE NOTE AT
	// THE TOP OF THIS ENUM ASKS FOR.** These checks were inline in `enforceOnce`
	// and half-inline in `Query`; extracting them as a shared stage (D253) is
	// the path itself changing, so it is a deliberate schema edit rather than a
	// string appearing in a warehouse.
	//
	// **IT REPLACES `REFUSED_BY_ANZEN`, WHICH `Query` WAS USING FOR AN OPEN
	// BREAKER AND WHICH IS WRONG BY THIS ENUM'S OWN DEFINITION** — anzen is "a
	// ceiling no grant can exceed, CHECKED BEFORE POLICY, which is what makes it
	// a ceiling rather than an opinion", and the meter runs after policy, after
	// resolve, immediately before the call. D201 is the precedent and the
	// warning: a credential downgrade once recorded as a residency conflict,
	// where "the control fired correctly and the record explained it wrongly,
	// which is worse than either alone".
	//
	// ONE VALUE FOR BOTH CONTROLS, with `kind` telling them apart
	// (`rate_limited` against `target_unavailable`). That is D138's split — a
	// coarse stage for routing and a fine taxonomy word for the reason — and
	// the two controls share a stage because they share a remedy: wait.
	RefusedBy_REFUSED_BY_METER RefusedBy = 8
)

// Enum value maps for RefusedBy.
var (
	RefusedBy_name = map[int32]string{
		0: "REFUSED_BY_UNSPECIFIED",
		1: "REFUSED_BY_ANZEN",
		2: "REFUSED_BY_POLICY",
		3: "REFUSED_BY_RESIDENCY",
		4: "REFUSED_BY_WITHDRAWAL",
		5: "REFUSED_BY_CREDENTIAL",
		6: "REFUSED_BY_CONFIGURATION",
		7: "REFUSED_BY_REQUEST",
		8: "REFUSED_BY_METER",
	}
	RefusedBy_value = map[string]int32{
		"REFUSED_BY_UNSPECIFIED":   0,
		"REFUSED_BY_ANZEN":         1,
		"REFUSED_BY_POLICY":        2,
		"REFUSED_BY_RESIDENCY":     3,
		"REFUSED_BY_WITHDRAWAL":    4,
		"REFUSED_BY_CREDENTIAL":    5,
		"REFUSED_BY_CONFIGURATION": 6,
		"REFUSED_BY_REQUEST":       7,
		"REFUSED_BY_METER":         8,
	}
)

func (x RefusedBy) Enum() *RefusedBy {
	p := new(RefusedBy)
	*p = x
	return p
}

func (x RefusedBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefusedBy) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_decision_proto_enumTypes[0].Descriptor()
}

func (RefusedBy) Type() protoreflect.EnumType {
	return &file_sekizui_v1_decision_proto_enumTypes[0]
}

func (x RefusedBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefusedBy.Descriptor instead.
func (RefusedBy) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{0}
}

type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_INTENT      Phase = 1 // written BEFORE the side effect
	Phase_PHASE_OUTCOME     Phase = 2 // written after
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_INTENT",
		2: "PHASE_OUTCOME",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_INTENT":      1,
		"PHASE_OUTCOME":     2,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_decision_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_sekizui_v1_decision_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{1}
}

type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_ALLOW       Verdict = 1
	Verdict_VERDICT_DENY        Verdict = 2
	Verdict_VERDICT_ESCALATE    Verdict = 3
	// Shadow mode (§4.11.4 item 3) and dry_run. Evaluated fully, no side effect.
	Verdict_VERDICT_WOULD_HAVE_FIRED Verdict = 4
	// Blast-radius budget or causation depth cap tripped. Audited even for bus->bus
	// reflexes that otherwise skip decision records, because a tripped guard is a
	// governance event regardless of whether an external system was touched (D23).
	Verdict_VERDICT_BUDGET_EXCEEDED Verdict = 5
	// A DECLARED LOSS (D174, D275): a poll was interrupted, the source cannot
	// re-read its window, and these events may never have reached a consumer.
	// Written by Sekizui, never by a connector, and naming the events — so a
	// gap somebody declared is distinguishable from one somebody is hiding (D77).
	Verdict_VERDICT_GAP Verdict = 6
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_ALLOW",
		2: "VERDICT_DENY",
		3: "VERDICT_ESCALATE",
		4: "VERDICT_WOULD_HAVE_FIRED",
		5: "VERDICT_BUDGET_EXCEEDED",
		6: "VERDICT_GAP",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED":      0,
		"VERDICT_ALLOW":            1,
		"VERDICT_DENY":             2,
		"VERDICT_ESCALATE":         3,
		"VERDICT_WOULD_HAVE_FIRED": 4,
		"VERDICT_BUDGET_EXCEEDED":  5,
		"VERDICT_GAP":              6,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_decision_proto_enumTypes[2].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_sekizui_v1_decision_proto_enumTypes[2]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{2}
}

type Decision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase Phase                  `protobuf:"varint,2,opt,name=phase,proto3,enum=sekizui.v1.Phase" json:"phase,omitempty"`
	At    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=at,proto3" json:"at,omitempty"`
	// FULL identity, EMBEDDED — not a reference to a request record (D39).
	//
	// Each row must be independently readable years later with no joins, must
	// survive config changes, and must export to a SIEM as a self-contained fact.
	// Storage is the cheapest thing in this design; duplication is the right trade.
	Identity  *Identity `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"`
	Action    string    `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	TargetRef string    `protobuf:"bytes,6,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	// Residency of the data touched. The audit sink must honour this, or shipping
	// EU-resident records to a US warehouse makes the audit log itself the
	// violation (D29 item 4).
	Residency string `protobuf:"bytes,7,opt,name=residency,proto3" json:"residency,omitempty"`
	// ALWAYS POPULATED, AND `VERDICT_UNSPECIFIED` IN A RECORD IS A DEFECT RATHER
	// THAN A CATEGORY (D228). A row with no verdict is invisible to every query
	// that filters on one, and a row that keeps an earlier stage's ALLOW after a
	// later stage refused the command asserts that something which never happened
	// was permitted. `gateway.refuse` floors this at VERDICT_DENY for exactly that
	// reason; the fine-grained answer is `refused_by` plus `CommandResult.kind`,
	// because this axis is deliberately coarse (D138) and collapses a policy
	// denial, an unauthenticated caller, a residency ceiling and a malformed
	// request into one word.
	Verdict Verdict `protobuf:"varint,8,opt,name=verdict,proto3,enum=sekizui.v1.Verdict" json:"verdict,omitempty"`
	// WHICH Rego rule matched. Without this, "allowed" is unexplainable — and an
	// unexplainable allow is not an audit record, it is a log line.
	MatchedRule string `protobuf:"bytes,9,opt,name=matched_rule,json=matchedRule,proto3" json:"matched_rule,omitempty"`
	// Why, when verdict is DENY or ESCALATE.
	Reason string `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	// What TRIGGERED this, as distinct from identity.chain (who AUTHORISED it).
	// Populated when a reflex or another command caused this.
	Causation      *Causation `protobuf:"bytes,11,opt,name=causation,proto3" json:"causation,omitempty"`
	IdempotencyKey string     `protobuf:"bytes,12,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Populated on phase == OUTCOME.
	Effect *Effect `protobuf:"bytes,13,opt,name=effect,proto3" json:"effect,omitempty"`
	// Hash of the previous record in this WAL segment — tamper-evidence for a few
	// lines of code (§5.4).
	PrevHash []byte `protobuf:"bytes,14,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	// Set when this decision came from a reflex, so reflex behaviour is queryable
	// independently of agent behaviour.
	ReflexName string `protobuf:"bytes,15,opt,name=reflex_name,json=reflexName,proto3" json:"reflex_name,omitempty"`
	// Set ONLY for a break-glass withdrawal (D106). Absent on every other row.
	Revocation *Revocation `protobuf:"bytes,16,opt,name=revocation,proto3" json:"revocation,omitempty"`
	// Set ONLY for a `restore_target` (D133), the verb that lifts a withdrawal.
	Restoration *Restoration `protobuf:"bytes,17,opt,name=restoration,proto3" json:"restoration,omitempty"`
	// WHICH STAGE refused this, when it was refused (D135). Unspecified on an
	// allowed command.
	RefusedBy RefusedBy `protobuf:"varint,18,opt,name=refused_by,json=refusedBy,proto3,enum=sekizui.v1.RefusedBy" json:"refused_by,omitempty"`
	// The IDENTITY of the configuration that authorised this call (D149) — a
	// hex SHA-256 over the compiled document, set on every row.
	//
	// §4.9a.2 promised this and named `Document.Version` as the mechanism. Version
	// is a PROVENANCE label supplied by the source (`<file>@<mtime>` absent an
	// etag), and provenance cannot answer the question an audit row asks: the same
	// configuration deployed twice has two mtimes, and `touch -r` gives two
	// different configurations one. An identity derived from CONTENT answers it in
	// both directions.
	//
	// Version stays where it is useful — the boot log carries both, so a hash here
	// joins back to a file there.
	ConfigIdentity string `protobuf:"bytes,19,opt,name=config_identity,json=configIdentity,proto3" json:"config_identity,omitempty"`
	// The credential's SECURITY POSTURE at the moment of this call (D100, D119).
	//
	// Absent on rows that resolved no credential — a refusal before resolve, or a
	// break-glass verb.
	CredentialPosture *CredentialPosture `protobuf:"bytes,20,opt,name=credential_posture,json=credentialPosture,proto3" json:"credential_posture,omitempty"`
	// Trace is the W3C span context this decision belongs to (D216).
	//
	// **ON THE DECISION RATHER THAN INSIDE `Identity`, which is where a bare
	// trace_id has lived since P0 and where it does not belong.** Identity
	// answers WHO — caller proven, subject asserted, the chain between them. A
	// trace answers WHICH CONVERSATION, which is request scope. The symptom of
	// the old placement is in the tree: `reflex.go` copies `env.GetTraceId()`
	// into a minted identity, plumbing a correlation value through an
	// authorisation struct because that is where the field happened to live. Both
	// sibling per-decision facts went here instead — `config_identity` (D149) and
	// `credential_posture` (D119).
	//
	// `Identity.trace_id` is KEPT and mirrors `trace.trace_id`, deprecated in
	// place: decision records outlive the code that wrote them by years, so a
	// field already in somebody's archive must keep meaning what it meant.
	Trace *Trace `protobuf:"bytes,21,opt,name=trace,proto3" json:"trace,omitempty"`
	// WHAT A `Describe` DISCLOSED, and the reason this row exists at all (D166).
	//
	// **D79 REFUSED TO AUDIT `Describe` AND THIS AMENDS THAT HALF.** Its argument
	// was dilution — "a row per enumeration would dilute a log whose value is
	// that every row is an action" — and the presence of this sub-message is what
	// turns that into a FILTER rather than a loss, in the shape `Revocation` and
	// `Restoration` already established for rows that are not ordinary commands.
	// The deciding argument was not completeness but TAMPER-EVIDENCE: the only
	// identity-carrying trace of enumeration was a log line, self-describe is
	// DEBUG (D126), and CONTRACTS 28 says that log silently loses records on
	// rotation. In a system whose default is to assume the environment is
	// compromised, the reconnaissance trace is the first thing an attacker wants
	// gone, and it was the one trace outside the hash chain.
	Disclosure    *Disclosure `protobuf:"bytes,22,opt,name=disclosure,proto3" json:"disclosure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_sekizui_v1_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{0}
}

func (x *Decision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Decision) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Decision) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *Decision) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Decision) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Decision) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *Decision) GetResidency() string {
	if x != nil {
		return x.Residency
	}
	return ""
}

func (x *Decision) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *Decision) GetMatchedRule() string {
	if x != nil {
		return x.MatchedRule
	}
	return ""
}

func (x *Decision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Decision) GetCausation() *Causation {
	if x != nil {
		return x.Causation
	}
	return nil
}

func (x *Decision) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Decision) GetEffect() *Effect {
	if x != nil {
		return x.Effect
	}
	return nil
}

func (x *Decision) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *Decision) GetReflexName() string {
	if x != nil {
		return x.ReflexName
	}
	return ""
}

func (x *Decision) GetRevocation() *Revocation {
	if x != nil {
		return x.Revocation
	}
	return nil
}

func (x *Decision) GetRestoration() *Restoration {
	if x != nil {
		return x.Restoration
	}
	return nil
}

func (x *Decision) GetRefusedBy() RefusedBy {
	if x != nil {
		return x.RefusedBy
	}
	return RefusedBy_REFUSED_BY_UNSPECIFIED
}

func (x *Decision) GetConfigIdentity() string {
	if x != nil {
		return x.ConfigIdentity
	}
	return ""
}

func (x *Decision) GetCredentialPosture() *CredentialPosture {
	if x != nil {
		return x.CredentialPosture
	}
	return nil
}

func (x *Decision) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Decision) GetDisclosure() *Disclosure {
	if x != nil {
		return x.Disclosure
	}
	return nil
}

// Trace is the W3C span context a decision or command belongs to (D216).
//
// **A BARE TRACE ID CANNOT PARENT A SPAN, which is the defect this replaces.**
// W3C Trace Context is `00-<32 hex trace-id>-<16 hex span-id>-<flags>`; keeping
// only the trace id means a span can be placed in the right TRACE and cannot be
// made a CHILD of the caller's span. Every governed call would then appear as a
// detached root beside the work that requested it — which is worse than no span,
// because it looks like a trace and shows the wrong causal shape.
type Trace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TraceId is the 16-byte W3C trace id, as 32 lowercase hex characters.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// ParentSpanId is the CALLER's span, so ours can be its child.
	//
	// Empty when the caller sent no `traceparent` — a legitimate case, and the
	// reason this is not validated into existence: a deployment whose clients do
	// not propagate trace context still gets correlation by trace id, and
	// inventing a parent would claim a causal link nobody asserted.
	ParentSpanId string `protobuf:"bytes,2,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	// Sampled is the caller's sampling decision, from the `traceparent` flags.
	//
	// **PROPAGATED UNCHANGED, NEVER OVERRIDDEN (D216).** The tempting move is to
	// force-keep any trace that produced a governed decision, since that is the
	// most interesting trace there is. It is refused for the downstream half: a
	// governance system that silently multiplies a customer's telemetry bill has
	// made an operational decision that was not its to make. What Sekizui does
	// instead is export its OWN span regardless — it already pays an fsync per
	// decision, so a span is cheaper than what it does unconditionally already.
	Sampled bool `protobuf:"varint,3,opt,name=sampled,proto3" json:"sampled,omitempty"`
	// SpanID is the span Sekizui minted for this command's outbound call.
	//
	// **IT LANDS WITH ITS WRITER, WHICH IS WHY THE NOTE THAT STOOD HERE SAID
	// NOTHING WOULD (D216, D235).** There was no tracer to mint one, and a field
	// nothing populates is the defect this schema keeps refusing — the same
	// reason `RefusedBy` has no `REFUSED_BY_DRIVER` member. `internal/tracing`
	// mints it now, in process and with no vendor SDK, W3C shaped: 8 random bytes
	// as 16 lowercase hex characters.
	//
	// EMPTY WHEN NO OUTBOUND CALL WAS MADE, which is most refusals: a command
	// stopped at a ceiling never reached a driver, so there is no span for it and
	// an id here would name one that does not exist.
	SpanId        string `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trace) Reset() {
	*x = Trace{}
	mi := &file_sekizui_v1_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trace) ProtoMessage() {}

func (x *Trace) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trace.ProtoReflect.Descriptor instead.
func (*Trace) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{1}
}

func (x *Trace) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Trace) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Trace) GetSampled() bool {
	if x != nil {
		return x.Sampled
	}
	return false
}

func (x *Trace) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

// CredentialPosture is metadata ABOUT the credential used, never the credential
// (D119).
//
// **THE MATERIAL IS NEVER IN HERE AND NEVER BECOMES A FIELD.** D119 is explicit,
// and the reason is that a field name is the only documentation most readers
// get: an earlier draft called `at_rest` "material", which read as though the
// bytes might be present. Renamed for that reason alone.
//
// WHY THE RECORD AND NOT ONLY THE BOOT LOG. D104's report states the posture
// once, at startup, to whoever is watching a terminal. An auditor asking "which
// targets were reachable with an unrotatable credential last quarter" cannot
// answer that from a log line nobody kept — they need it per action, which is
// what §5.4 means by a record that stands alone. D118 is what makes the richer
// record safe: decisions provably reach no bus consumer, so the reconnaissance
// concern that argued for restraint does not apply.
type CredentialPosture struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Scheme is where material came from: "file", "env", "ambient", "gcp-sm".
	//
	// D100 originally specified this ALONE. D119 widened it, because a scheme
	// tells a reviewer the mechanism and not the properties — `file://` spans a
	// projected volume that rotates and a subPath mount that cannot.
	Scheme string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	// Version is what the provider reported RESOLVING TO, not what configuration
	// asked for (D130).
	//
	// The distinction is the whole point under a tracking reference: config says
	// `versions/latest` forever while the live version moves, so this is what
	// keeps "what was in use at 14:03" answerable from Sekizui's own records
	// instead of by correlating two systems. Empty where the provider cannot say,
	// which for a content-addressed source is the honest answer.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Rotation is "live", "on-change" or "NONE" (D104).
	//
	// A STRING, not an enum, following `kind`'s precedent (D138): the vocabulary
	// grows with the providers, and a proto enum shadowing a Go one is a second
	// vocabulary whose divergence is silent.
	Rotation string `protobuf:"bytes,3,opt,name=rotation,proto3" json:"rotation,omitempty"`
	// AuditedReads is whether the SOURCE records who read this credential and
	// when — true for a secret manager, false for a mounted file.
	AuditedReads bool `protobuf:"varint,4,opt,name=audited_reads,json=auditedReads,proto3" json:"audited_reads,omitempty"`
	// AtRest is WHERE THE BYTES LIVE: "secret-manager", "k8s-secret",
	// "static-file", "platform". Never the bytes themselves.
	//
	// This is the field that answers the SOPS misconception without anybody
	// needing to know it in advance — `helm-secrets` encrypts version control and
	// leaves the material in a Kubernetes Secret, and this column says so (D103).
	AtRest        string `protobuf:"bytes,5,opt,name=at_rest,json=atRest,proto3" json:"at_rest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialPosture) Reset() {
	*x = CredentialPosture{}
	mi := &file_sekizui_v1_decision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialPosture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialPosture) ProtoMessage() {}

func (x *CredentialPosture) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_decision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialPosture.ProtoReflect.Descriptor instead.
func (*CredentialPosture) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{2}
}

func (x *CredentialPosture) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *CredentialPosture) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CredentialPosture) GetRotation() string {
	if x != nil {
		return x.Rotation
	}
	return ""
}

func (x *CredentialPosture) GetAuditedReads() bool {
	if x != nil {
		return x.AuditedReads
	}
	return false
}

func (x *CredentialPosture) GetAtRest() string {
	if x != nil {
		return x.AtRest
	}
	return ""
}

// Disclosure records what a capability enumeration revealed, and what shaped it.
//
// **DERIVED FROM THE RESPONSE THAT WAS ACTUALLY RETURNED**, never recomputed.
// The whole value of the row is that it says what the caller was told, so a
// record built by asking the catalog a second time could disagree with the
// answer it is supposed to describe — `stampPosture`'s lesson (D119) and D138's,
// applied to a disclosure instead of a refusal.
type Disclosure struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The principal whose capabilities were listed. Equal to the subject for the
	// common case; DIFFERENT is the reconnaissance shape D79 wrote its refusal
	// for, and it is the value an incident review greps for.
	PrincipalDescribed string `protobuf:"bytes,1,opt,name=principal_described,json=principalDescribed,proto3" json:"principal_described,omitempty"`
	// How many capabilities were advertised. A count rather than the list: the
	// list is reconstructible from the configuration of the day plus this row's
	// `config_identity` (D149), and a row per capability would be the dilution
	// D79 was right to refuse.
	Capabilities uint32 `protobuf:"varint,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// The shin lenses that shaped the answer, by name. IMPOSED applies whatever
	// the consumer asks for; AVAILABLE is what it may select (§4.12).
	//
	// Once a consumer learns available data shapes by asking a connector,
	// `Describe` IS a disclosure surface and shin governs disclosure — so a
	// disclosure shaped by a lens with no record of which lens applied is
	// "why does analytics never see user.email" moved from the payload to the
	// catalog.
	ImposedLenses   []string `protobuf:"bytes,3,rep,name=imposed_lenses,json=imposedLenses,proto3" json:"imposed_lenses,omitempty"`
	AvailableLenses []string `protobuf:"bytes,4,rep,name=available_lenses,json=availableLenses,proto3" json:"available_lenses,omitempty"`
	// The anzen rules that WITHHELD a capability, by name.
	//
	// `anzen.Guards.Forbids` has always returned the guard's name and the catalog
	// discarded it with `_`, so a consumer saw an absence with no explanation and
	// nothing recorded which rule shaped the advertisement (CONTRACTS 64). Not a
	// missing implementation and not a missing caller: a value discarded between
	// the two.
	WithheldBy    []string `protobuf:"bytes,5,rep,name=withheld_by,json=withheldBy,proto3" json:"withheld_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disclosure) Reset() {
	*x = Disclosure{}
	mi := &file_sekizui_v1_decision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disclosure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disclosure) ProtoMessage() {}

func (x *Disclosure) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_decision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disclosure.ProtoReflect.Descriptor instead.
func (*Disclosure) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{3}
}

func (x *Disclosure) GetPrincipalDescribed() string {
	if x != nil {
		return x.PrincipalDescribed
	}
	return ""
}

func (x *Disclosure) GetCapabilities() uint32 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

func (x *Disclosure) GetImposedLenses() []string {
	if x != nil {
		return x.ImposedLenses
	}
	return nil
}

func (x *Disclosure) GetAvailableLenses() []string {
	if x != nil {
		return x.AvailableLenses
	}
	return nil
}

func (x *Disclosure) GetWithheldBy() []string {
	if x != nil {
		return x.WithheldBy
	}
	return nil
}

// Restoration is what a `sekizui.restore_target` lifted.
//
// A SEPARATE MESSAGE FROM Revocation rather than a severity on it, because the
// fields that matter differ entirely: a withdrawal records what it STOPPED, a
// restoration records what it re-enabled and what state it found. Reusing
// `Revocation` would have left `cancelled_in_flight` and `stragglers` sitting
// at zero on every restore row, which reads as "cancelled nothing" rather than
// "not applicable".
type Restoration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WHO OR WHAT lifted it: "operator:agent:oncall", or "anzen:<rule>".
	Trigger string `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// WHICH severity was in force — "revoke_credential" or "quarantine_target".
	//
	// THE FIELD AN INCIDENT REVIEW ACTUALLY NEEDS. Lifting a quarantine is a
	// health decision about a misbehaving target; lifting a REVOCATION is a
	// security decision, and it asserts that a credential believed compromised is
	// now safe to use again. Those must not look the same in the log months
	// later, and only the row can say which happened.
	RestoredFrom  string `protobuf:"bytes,2,opt,name=restored_from,json=restoredFrom,proto3" json:"restored_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restoration) Reset() {
	*x = Restoration{}
	mi := &file_sekizui_v1_decision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restoration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restoration) ProtoMessage() {}

func (x *Restoration) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_decision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restoration.ProtoReflect.Descriptor instead.
func (*Restoration) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{4}
}

func (x *Restoration) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *Restoration) GetRestoredFrom() string {
	if x != nil {
		return x.RestoredFrom
	}
	return ""
}

// Revocation is what a `revoke_credential` or `quarantine_target` actually did.
//
// A SEPARATE MESSAGE RATHER THAN FIVE MORE Decision FIELDS, because these are
// meaningful together and meaningless apart: `cancelled_in_flight = 0` says
// nothing without the severity that produced it. Nesting also keeps the shape
// of an ordinary row unchanged — a reader who never sees a revocation never
// sees these fields, and a sink that does not understand them skips one
// submessage rather than five stray columns.
//
// D106: "every revocation writes a decision record naming the credential, the
// trigger, and the count of in-flight calls it cancelled. That last number is
// the one an incident review asks for and nothing else can reconstruct." A
// revocation that records only that it ran answers "did it fire" — the question
// actually asked is "what was still running when it did".
type Revocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which of the two severities ran (§4.7.10). Recorded as a string, matching
	// the anzen verb exactly — "revoke_credential" or "quarantine_target" — so a
	// query joins to the vocabulary rather than to an enum that has to be kept
	// in step with it.
	Severity string `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	// WHO OR WHAT fired it: "operator:agent:oncall" for the governed verb,
	// "anzen:<rule>" when a rule did. Distinct from identity, which says who
	// authenticated: an anzen rule firing at 03:00 has no human behind it, and
	// that fact is the point rather than a gap.
	Trigger string `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// In-flight calls this withdrawal CANCELLED. Always zero for a quarantine,
	// which lets them finish — the difference that makes the two severities two.
	CancelledInFlight uint32 `protobuf:"varint,4,opt,name=cancelled_in_flight,json=cancelledInFlight,proto3" json:"cancelled_in_flight,omitempty"`
	// In-flight calls deliberately left running. Always zero for a revocation.
	LeftRunning uint32 `protobuf:"varint,5,opt,name=left_running,json=leftRunning,proto3" json:"left_running,omitempty"`
	// Pooled entries evicted, and those that were session-oriented (§4.7.4 class
	// 3) and got a real Close rather than being dropped.
	Evicted  uint32 `protobuf:"varint,6,opt,name=evicted,proto3" json:"evicted,omitempty"`
	TornDown uint32 `protobuf:"varint,7,opt,name=torn_down,json=tornDown,proto3" json:"torn_down,omitempty"`
	// Entries whose drain did not finish inside the deadline — a driver that
	// ignored its context. Their material is NOT yet zeroed; the wipe is deferred
	// to whenever that call returns, never skipped (D127).
	//
	// RECORDED RATHER THAN RETRIED, because it is the one part of a revocation
	// that did not complete, and an incident review that reads "revoked" without
	// it would believe the material was gone when it was not.
	Stragglers uint32 `protobuf:"varint,8,opt,name=stragglers,proto3" json:"stragglers,omitempty"`
	// WHICH ANZEN RULE decided this withdrawal — "credential-compromise" — or
	// EMPTY when an operator improvised it (D134).
	//
	// EMPTY IS THE INTERESTING VALUE, and it is why this is a field rather than
	// an inference. Anzen holds the reasoning: a rule declares the subject and
	// the severity in daylight, reviewed by whoever is accountable, so an
	// operator at 03:00 pulls a lever rather than choosing between "the target is
	// misbehaving" and "the credential is compromised" under pressure. The raw
	// verb stays available, because §4.7.10 rules out any path needing a
	// redeploy and the unanticipated incident is what break-glass is for.
	//
	// So `decided_by = ""` marks a withdrawal nobody had planned. Querying for it
	// yields the list of decisions that ought to exist and do not — the log
	// surfacing a gap to patch, rather than the absence of a rule looking like
	// health. Distinct from `Decision.matched_rule`, which names the GRANT that
	// authorised the command, not the rule that decided it.
	DecidedBy     string `protobuf:"bytes,9,opt,name=decided_by,json=decidedBy,proto3" json:"decided_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Revocation) Reset() {
	*x = Revocation{}
	mi := &file_sekizui_v1_decision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Revocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revocation) ProtoMessage() {}

func (x *Revocation) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_decision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revocation.ProtoReflect.Descriptor instead.
func (*Revocation) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{5}
}

func (x *Revocation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Revocation) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *Revocation) GetCancelledInFlight() uint32 {
	if x != nil {
		return x.CancelledInFlight
	}
	return 0
}

func (x *Revocation) GetLeftRunning() uint32 {
	if x != nil {
		return x.LeftRunning
	}
	return 0
}

func (x *Revocation) GetEvicted() uint32 {
	if x != nil {
		return x.Evicted
	}
	return 0
}

func (x *Revocation) GetTornDown() uint32 {
	if x != nil {
		return x.TornDown
	}
	return 0
}

func (x *Revocation) GetStragglers() uint32 {
	if x != nil {
		return x.Stragglers
	}
	return 0
}

func (x *Revocation) GetDecidedBy() string {
	if x != nil {
		return x.DecidedBy
	}
	return ""
}

// Effect records what actually happened at the external system.
type Effect struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// HTTP status or driver-specific code.
	StatusCode int32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	LatencyMs  int64 `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Identifier created or affected, e.g. "PROJ-123". This is what makes the
	// audit trail joinable to the target system's own records.
	ExternalRef string `protobuf:"bytes,4,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Error       string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// How many attempts, including retries.
	Attempts uint32 `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	// Freeform driver detail. Never contains credentials — Secret is a
	// self-redacting type (§4.3.3), but this field is Struct, so drivers must not
	// put secrets here. Enforced by review and by the redacting slog handler.
	Detail        *structpb.Struct `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Effect) Reset() {
	*x = Effect{}
	mi := &file_sekizui_v1_decision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Effect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Effect) ProtoMessage() {}

func (x *Effect) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_decision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Effect.ProtoReflect.Descriptor instead.
func (*Effect) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_decision_proto_rawDescGZIP(), []int{6}
}

func (x *Effect) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Effect) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Effect) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Effect) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *Effect) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Effect) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Effect) GetDetail() *structpb.Struct {
	if x != nil {
		return x.Detail
	}
	return nil
}

var File_sekizui_v1_decision_proto protoreflect.FileDescriptor

const file_sekizui_v1_decision_proto_rawDesc = "" +
	"\n" +
	"\x19sekizui/v1/decision.proto\x12\n" +
	"sekizui.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15sekizui/v1/core.proto\x1a\x19sekizui/v1/envelope.proto\"\xa9\a\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x11.sekizui.v1.PhaseR\x05phase\x12*\n" +
	"\x02at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x120\n" +
	"\bidentity\x18\x04 \x01(\v2\x14.sekizui.v1.IdentityR\bidentity\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x06 \x01(\tR\ttargetRef\x12\x1c\n" +
	"\tresidency\x18\a \x01(\tR\tresidency\x12-\n" +
	"\averdict\x18\b \x01(\x0e2\x13.sekizui.v1.VerdictR\averdict\x12!\n" +
	"\fmatched_rule\x18\t \x01(\tR\vmatchedRule\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x123\n" +
	"\tcausation\x18\v \x01(\v2\x15.sekizui.v1.CausationR\tcausation\x12'\n" +
	"\x0fidempotency_key\x18\f \x01(\tR\x0eidempotencyKey\x12*\n" +
	"\x06effect\x18\r \x01(\v2\x12.sekizui.v1.EffectR\x06effect\x12\x1b\n" +
	"\tprev_hash\x18\x0e \x01(\fR\bprevHash\x12\x1f\n" +
	"\vreflex_name\x18\x0f \x01(\tR\n" +
	"reflexName\x126\n" +
	"\n" +
	"revocation\x18\x10 \x01(\v2\x16.sekizui.v1.RevocationR\n" +
	"revocation\x129\n" +
	"\vrestoration\x18\x11 \x01(\v2\x17.sekizui.v1.RestorationR\vrestoration\x124\n" +
	"\n" +
	"refused_by\x18\x12 \x01(\x0e2\x15.sekizui.v1.RefusedByR\trefusedBy\x12'\n" +
	"\x0fconfig_identity\x18\x13 \x01(\tR\x0econfigIdentity\x12L\n" +
	"\x12credential_posture\x18\x14 \x01(\v2\x1d.sekizui.v1.CredentialPostureR\x11credentialPosture\x12'\n" +
	"\x05trace\x18\x15 \x01(\v2\x11.sekizui.v1.TraceR\x05trace\x126\n" +
	"\n" +
	"disclosure\x18\x16 \x01(\v2\x16.sekizui.v1.DisclosureR\n" +
	"disclosure\"{\n" +
	"\x05Trace\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12$\n" +
	"\x0eparent_span_id\x18\x02 \x01(\tR\fparentSpanId\x12\x18\n" +
	"\asampled\x18\x03 \x01(\bR\asampled\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\tR\x06spanId\"\x9f\x01\n" +
	"\x11CredentialPosture\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\brotation\x18\x03 \x01(\tR\brotation\x12#\n" +
	"\raudited_reads\x18\x04 \x01(\bR\fauditedReads\x12\x17\n" +
	"\aat_rest\x18\x05 \x01(\tR\x06atRest\"\xd4\x01\n" +
	"\n" +
	"Disclosure\x12/\n" +
	"\x13principal_described\x18\x01 \x01(\tR\x12principalDescribed\x12\"\n" +
	"\fcapabilities\x18\x02 \x01(\rR\fcapabilities\x12%\n" +
	"\x0eimposed_lenses\x18\x03 \x03(\tR\rimposedLenses\x12)\n" +
	"\x10available_lenses\x18\x04 \x03(\tR\x0favailableLenses\x12\x1f\n" +
	"\vwithheld_by\x18\x05 \x03(\tR\n" +
	"withheldBy\"L\n" +
	"\vRestoration\x12\x18\n" +
	"\atrigger\x18\x01 \x01(\tR\atrigger\x12#\n" +
	"\rrestored_from\x18\x02 \x01(\tR\frestoredFrom\"\xa1\x02\n" +
	"\n" +
	"Revocation\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\x12.\n" +
	"\x13cancelled_in_flight\x18\x04 \x01(\rR\x11cancelledInFlight\x12!\n" +
	"\fleft_running\x18\x05 \x01(\rR\vleftRunning\x12\x18\n" +
	"\aevicted\x18\x06 \x01(\rR\aevicted\x12\x1b\n" +
	"\ttorn_down\x18\a \x01(\rR\btornDown\x12\x1e\n" +
	"\n" +
	"stragglers\x18\b \x01(\rR\n" +
	"stragglers\x12\x1d\n" +
	"\n" +
	"decided_by\x18\t \x01(\tR\tdecidedByJ\x04\b\x03\x10\x04R\x0ecredential_ref\"\xe8\x01\n" +
	"\x06Effect\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12!\n" +
	"\fexternal_ref\x18\x04 \x01(\tR\vexternalRef\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\rR\battempts\x12/\n" +
	"\x06detail\x18\a \x01(\v2\x17.google.protobuf.StructR\x06detail*\xf0\x01\n" +
	"\tRefusedBy\x12\x1a\n" +
	"\x16REFUSED_BY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10REFUSED_BY_ANZEN\x10\x01\x12\x15\n" +
	"\x11REFUSED_BY_POLICY\x10\x02\x12\x18\n" +
	"\x14REFUSED_BY_RESIDENCY\x10\x03\x12\x19\n" +
	"\x15REFUSED_BY_WITHDRAWAL\x10\x04\x12\x19\n" +
	"\x15REFUSED_BY_CREDENTIAL\x10\x05\x12\x1c\n" +
	"\x18REFUSED_BY_CONFIGURATION\x10\x06\x12\x16\n" +
	"\x12REFUSED_BY_REQUEST\x10\a\x12\x14\n" +
	"\x10REFUSED_BY_METER\x10\b*C\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPHASE_INTENT\x10\x01\x12\x11\n" +
	"\rPHASE_OUTCOME\x10\x02*\xa9\x01\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rVERDICT_ALLOW\x10\x01\x12\x10\n" +
	"\fVERDICT_DENY\x10\x02\x12\x14\n" +
	"\x10VERDICT_ESCALATE\x10\x03\x12\x1c\n" +
	"\x18VERDICT_WOULD_HAVE_FIRED\x10\x04\x12\x1b\n" +
	"\x17VERDICT_BUDGET_EXCEEDED\x10\x05\x12\x0f\n" +
	"\vVERDICT_GAP\x10\x06B\xa9\x01\n" +
	"\x0ecom.sekizui.v1B\rDecisionProtoP\x01Z?github.com/fullstorydev/sekizui/pkg/schema/sekizui/v1;sekizuiv1\xa2\x02\x03SXX\xaa\x02\n" +
	"Sekizui.V1\xca\x02\n" +
	"Sekizui\\V1\xe2\x02\x16Sekizui\\V1\\GPBMetadata\xea\x02\vSekizui::V1b\x06proto3"

var (
	file_sekizui_v1_decision_proto_rawDescOnce sync.Once
	file_sekizui_v1_decision_proto_rawDescData []byte
)

func file_sekizui_v1_decision_proto_rawDescGZIP() []byte {
	file_sekizui_v1_decision_proto_rawDescOnce.Do(func() {
		file_sekizui_v1_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sekizui_v1_decision_proto_rawDesc), len(file_sekizui_v1_decision_proto_rawDesc)))
	})
	return file_sekizui_v1_decision_proto_rawDescData
}

var file_sekizui_v1_decision_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sekizui_v1_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sekizui_v1_decision_proto_goTypes = []any{
	(RefusedBy)(0),                // 0: sekizui.v1.RefusedBy
	(Phase)(0),                    // 1: sekizui.v1.Phase
	(Verdict)(0),                  // 2: sekizui.v1.Verdict
	(*Decision)(nil),              // 3: sekizui.v1.Decision
	(*Trace)(nil),                 // 4: sekizui.v1.Trace
	(*CredentialPosture)(nil),     // 5: sekizui.v1.CredentialPosture
	(*Disclosure)(nil),            // 6: sekizui.v1.Disclosure
	(*Restoration)(nil),           // 7: sekizui.v1.Restoration
	(*Revocation)(nil),            // 8: sekizui.v1.Revocation
	(*Effect)(nil),                // 9: sekizui.v1.Effect
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*Identity)(nil),              // 11: sekizui.v1.Identity
	(*Causation)(nil),             // 12: sekizui.v1.Causation
	(*structpb.Struct)(nil),       // 13: google.protobuf.Struct
}
var file_sekizui_v1_decision_proto_depIdxs = []int32{
	1,  // 0: sekizui.v1.Decision.phase:type_name -> sekizui.v1.Phase
	10, // 1: sekizui.v1.Decision.at:type_name -> google.protobuf.Timestamp
	11, // 2: sekizui.v1.Decision.identity:type_name -> sekizui.v1.Identity
	2,  // 3: sekizui.v1.Decision.verdict:type_name -> sekizui.v1.Verdict
	12, // 4: sekizui.v1.Decision.causation:type_name -> sekizui.v1.Causation
	9,  // 5: sekizui.v1.Decision.effect:type_name -> sekizui.v1.Effect
	8,  // 6: sekizui.v1.Decision.revocation:type_name -> sekizui.v1.Revocation
	7,  // 7: sekizui.v1.Decision.restoration:type_name -> sekizui.v1.Restoration
	0,  // 8: sekizui.v1.Decision.refused_by:type_name -> sekizui.v1.RefusedBy
	5,  // 9: sekizui.v1.Decision.credential_posture:type_name -> sekizui.v1.CredentialPosture
	4,  // 10: sekizui.v1.Decision.trace:type_name -> sekizui.v1.Trace
	6,  // 11: sekizui.v1.Decision.disclosure:type_name -> sekizui.v1.Disclosure
	13, // 12: sekizui.v1.Effect.detail:type_name -> google.protobuf.Struct
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_sekizui_v1_decision_proto_init() }
func file_sekizui_v1_decision_proto_init() {
	if File_sekizui_v1_decision_proto != nil {
		return
	}
	file_sekizui_v1_core_proto_init()
	file_sekizui_v1_envelope_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sekizui_v1_decision_proto_rawDesc), len(file_sekizui_v1_decision_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sekizui_v1_decision_proto_goTypes,
		DependencyIndexes: file_sekizui_v1_decision_proto_depIdxs,
		EnumInfos:         file_sekizui_v1_decision_proto_enumTypes,
		MessageInfos:      file_sekizui_v1_decision_proto_msgTypes,
	}.Build()
	File_sekizui_v1_decision_proto = out.File
	file_sekizui_v1_decision_proto_goTypes = nil
	file_sekizui_v1_decision_proto_depIdxs = nil
}
