// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sekizui/v1/envelope.proto

package sekizuiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique envelope ID (ULID — sortable, so it doubles as a coarse ordering key).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// CloudEvents `source`: the target ref that produced this.
	// e.g. "fullstory:o-EXAMPLE-na1", "jira:acme".
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// CloudEvents spec version. "1.0".
	SpecVersion string `protobuf:"bytes,3,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`
	// Versioned payload type: "fullstory.rage_click.v1" (D41).
	//
	// Evolution rules that make most changes non-events:
	//   - consumers MUST ignore unknown fields
	//   - adding an OPTIONAL field is not a version bump
	//   - removing / renaming / retyping / requiring a field IS
	//   - both versions may be published simultaneously during migration
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Primary entity this concerns: session ID, issue key, user ID.
	Subject string `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	// Event time at the source.
	Time *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time,proto3" json:"time,omitempty"`
	// URI of the registered JSON Schema describing `data` (D40).
	// CloudEvents `dataschema` — using the spec as intended, not bending it.
	DataSchema string `protobuf:"bytes,7,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`
	// The payload. Validated against data_schema at publish time.
	Data *structpb.Struct `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	// What produced this envelope, and how deep the chain is (D19).
	//
	// REQUIRED FROM v1. Reflex loop detection is impossible without it, and
	// retrofitting means a schema migration plus a window during which runaway
	// reflexes cannot be detected. This is the one field that must not be deferred.
	Causation *Causation `protobuf:"bytes,9,opt,name=causation,proto3" json:"causation,omitempty"`
	// Pipeline stage, e.g. "raw", "enriched", "triaged", "judged".
	//
	// A STRING, not an enum (D43). Stages are a configured ordered list, so the set
	// is extensible — someone can insert "normalised" between raw and enriched
	// without touching this file. Monotonicity (D21) is checked against the
	// configured order.
	Stage string `protobuf:"bytes,10,opt,name=stage,proto3" json:"stage,omitempty"`
	// Residency classification, e.g. "eu", "us" (D29). Sinks and egress drivers
	// enforce it downstream; the audit sink must respect it too, or the audit log
	// itself becomes the violation.
	Residency string `protobuf:"bytes,11,opt,name=residency,proto3" json:"residency,omitempty"`
	// Correlates with Identity.trace_id and Decision.identity.trace_id.
	TraceId string `protobuf:"bytes,12,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// When Sekizui observed it, as distinct from `time` (when it happened).
	// The gap between these two is the ingest lag, and worth graphing.
	ObservedTime *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=observed_time,json=observedTime,proto3" json:"observed_time,omitempty"`
	// Optional compact, token-budget-aware view for LLM consumption (§4.6.2).
	// Generated by a stateless enrichment reflex, not by translator code — so it is
	// data-defined and tunable per consumer.
	Projection    *structpb.Struct `protobuf:"bytes,14,opt,name=projection,proto3" json:"projection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_sekizui_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Envelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Envelope) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

func (x *Envelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Envelope) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Envelope) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Envelope) GetDataSchema() string {
	if x != nil {
		return x.DataSchema
	}
	return ""
}

func (x *Envelope) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Envelope) GetCausation() *Causation {
	if x != nil {
		return x.Causation
	}
	return nil
}

func (x *Envelope) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Envelope) GetResidency() string {
	if x != nil {
		return x.Residency
	}
	return ""
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetObservedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedTime
	}
	return nil
}

func (x *Envelope) GetProjection() *structpb.Struct {
	if x != nil {
		return x.Projection
	}
	return nil
}

// Causation records WHAT TRIGGERED something.
//
// Distinct from Identity.chain, which records WHO AUTHORISED it. A reflex firing
// on event E has chain ["reflex:R"] and causation E. Both are audited; they answer
// different incident-review questions.
type Causation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The originating envelope at the root of this chain.
	RootId string `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// The immediate predecessor.
	ParentId string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Hop count from root. Capped to break runaway loops (§4.11.4 item 2).
	//
	// Note this is the BACKSTOP, not the primary guarantee. Cycles are prevented
	// structurally by stage monotonicity (D21); depth catches bugs and
	// agent-produced events re-entering the pipeline.
	Depth uint32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	// What emitted this: "translator:jira", "reflex:checkout-friction",
	// "command:<decision_id>", "agent:triage".
	ProducedBy string `protobuf:"bytes,4,opt,name=produced_by,json=producedBy,proto3" json:"produced_by,omitempty"`
	// The audit decision under which this envelope was produced — for a polled
	// envelope, the INTENT row its poll wrote before publishing (P3 step 7,
	// D272). Joinable to the log, where the intent's outcome says how many
	// events the poll published. Empty for an envelope no decision produced (a
	// reflex enrichment, which is not recorded per envelope).
	DecisionId    string `protobuf:"bytes,5,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Causation) Reset() {
	*x = Causation{}
	mi := &file_sekizui_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Causation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Causation) ProtoMessage() {}

func (x *Causation) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Causation.ProtoReflect.Descriptor instead.
func (*Causation) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *Causation) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *Causation) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Causation) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Causation) GetProducedBy() string {
	if x != nil {
		return x.ProducedBy
	}
	return ""
}

func (x *Causation) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

var File_sekizui_v1_envelope_proto protoreflect.FileDescriptor

const file_sekizui_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x19sekizui/v1/envelope.proto\x12\n" +
	"sekizui.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x03\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12!\n" +
	"\fspec_version\x18\x03 \x01(\tR\vspecVersion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12.\n" +
	"\x04time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1f\n" +
	"\vdata_schema\x18\a \x01(\tR\n" +
	"dataSchema\x12+\n" +
	"\x04data\x18\b \x01(\v2\x17.google.protobuf.StructR\x04data\x123\n" +
	"\tcausation\x18\t \x01(\v2\x15.sekizui.v1.CausationR\tcausation\x12\x14\n" +
	"\x05stage\x18\n" +
	" \x01(\tR\x05stage\x12\x1c\n" +
	"\tresidency\x18\v \x01(\tR\tresidency\x12\x19\n" +
	"\btrace_id\x18\f \x01(\tR\atraceId\x12?\n" +
	"\robserved_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\fobservedTime\x127\n" +
	"\n" +
	"projection\x18\x0e \x01(\v2\x17.google.protobuf.StructR\n" +
	"projection\"\x99\x01\n" +
	"\tCausation\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\rR\x05depth\x12\x1f\n" +
	"\vproduced_by\x18\x04 \x01(\tR\n" +
	"producedBy\x12\x1f\n" +
	"\vdecision_id\x18\x05 \x01(\tR\n" +
	"decisionIdB\xa9\x01\n" +
	"\x0ecom.sekizui.v1B\rEnvelopeProtoP\x01Z?github.com/fullstorydev/sekizui/pkg/schema/sekizui/v1;sekizuiv1\xa2\x02\x03SXX\xaa\x02\n" +
	"Sekizui.V1\xca\x02\n" +
	"Sekizui\\V1\xe2\x02\x16Sekizui\\V1\\GPBMetadata\xea\x02\vSekizui::V1b\x06proto3"

var (
	file_sekizui_v1_envelope_proto_rawDescOnce sync.Once
	file_sekizui_v1_envelope_proto_rawDescData []byte
)

func file_sekizui_v1_envelope_proto_rawDescGZIP() []byte {
	file_sekizui_v1_envelope_proto_rawDescOnce.Do(func() {
		file_sekizui_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sekizui_v1_envelope_proto_rawDesc), len(file_sekizui_v1_envelope_proto_rawDesc)))
	})
	return file_sekizui_v1_envelope_proto_rawDescData
}

var file_sekizui_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sekizui_v1_envelope_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: sekizui.v1.Envelope
	(*Causation)(nil),             // 1: sekizui.v1.Causation
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
}
var file_sekizui_v1_envelope_proto_depIdxs = []int32{
	2, // 0: sekizui.v1.Envelope.time:type_name -> google.protobuf.Timestamp
	3, // 1: sekizui.v1.Envelope.data:type_name -> google.protobuf.Struct
	1, // 2: sekizui.v1.Envelope.causation:type_name -> sekizui.v1.Causation
	2, // 3: sekizui.v1.Envelope.observed_time:type_name -> google.protobuf.Timestamp
	3, // 4: sekizui.v1.Envelope.projection:type_name -> google.protobuf.Struct
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_sekizui_v1_envelope_proto_init() }
func file_sekizui_v1_envelope_proto_init() {
	if File_sekizui_v1_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sekizui_v1_envelope_proto_rawDesc), len(file_sekizui_v1_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sekizui_v1_envelope_proto_goTypes,
		DependencyIndexes: file_sekizui_v1_envelope_proto_depIdxs,
		MessageInfos:      file_sekizui_v1_envelope_proto_msgTypes,
	}.Build()
	File_sekizui_v1_envelope_proto = out.File
	file_sekizui_v1_envelope_proto_goTypes = nil
	file_sekizui_v1_envelope_proto_depIdxs = nil
}
