// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sekizui/v1/seiren.proto

package sekizuiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SeirenGapKind says what a gap MEANS for the key — the difference a consumer
// must not have to parse out of `reason`.
type SeirenGapKind int32

const (
	SeirenGapKind_SEIREN_GAP_KIND_UNSPECIFIED SeirenGapKind = 0
	// The key is ABSENT: the rule could not run for this caller (a lens withheld
	// a path it reads) or not over this result (a row was not admitted).
	SeirenGapKind_SEIREN_GAP_KIND_UNAVAILABLE SeirenGapKind = 1
	// The key is PRESENT and PARTIAL: a `list` or `count` kept `limit` items of
	// more (D300's limit, CONTRACTS 146).
	SeirenGapKind_SEIREN_GAP_KIND_TRUNCATED SeirenGapKind = 2
)

// Enum value maps for SeirenGapKind.
var (
	SeirenGapKind_name = map[int32]string{
		0: "SEIREN_GAP_KIND_UNSPECIFIED",
		1: "SEIREN_GAP_KIND_UNAVAILABLE",
		2: "SEIREN_GAP_KIND_TRUNCATED",
	}
	SeirenGapKind_value = map[string]int32{
		"SEIREN_GAP_KIND_UNSPECIFIED": 0,
		"SEIREN_GAP_KIND_UNAVAILABLE": 1,
		"SEIREN_GAP_KIND_TRUNCATED":   2,
	}
)

func (x SeirenGapKind) Enum() *SeirenGapKind {
	p := new(SeirenGapKind)
	*p = x
	return p
}

func (x SeirenGapKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeirenGapKind) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_seiren_proto_enumTypes[0].Descriptor()
}

func (SeirenGapKind) Type() protoreflect.EnumType {
	return &file_sekizui_v1_seiren_proto_enumTypes[0]
}

func (x SeirenGapKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeirenGapKind.Descriptor instead.
func (SeirenGapKind) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_seiren_proto_rawDescGZIP(), []int{0}
}

// Seiren is one refinement of one result.
//
// **THE CONNECTOR TYPES `value`; THE ENGINE OWNS THE REST (D317).** `window`
// and `unavailable` are produced identically for every seiren type, so they are
// declared once here rather than restated by every connector's schema with
// nothing checking the copies agree — which is how D317 revised D300.
type Seiren struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The seiren type every applied rule writes, including version —
	// "fullstory.session_context.v1". Registered and owned by the connector.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// One key per rule that ran and matched, typed by `type`'s schema and lensed
	// for the caller like any payload. A `first` that found nothing writes no
	// key: read an absent key together with `window`.
	Value *structpb.Struct `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// What the seiren covers.
	Window *SeirenWindow `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	// Everything the seiren could not give in full, one entry per key — so a
	// partial seiren never reads as complete (D300, D317). TYPED, so the list
	// grows by a kind rather than a field: a key a rule could not write at all,
	// a key it wrote only in part, and in P5 a lookup its budget or deadline
	// refused (D298).
	Gaps []*SeirenGap `protobuf:"bytes,4,rep,name=gaps,proto3" json:"gaps,omitempty"`
	// The rules that ran, sorted.
	Rules         []string `protobuf:"bytes,5,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seiren) Reset() {
	*x = Seiren{}
	mi := &file_sekizui_v1_seiren_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seiren) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seiren) ProtoMessage() {}

func (x *Seiren) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_seiren_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seiren.ProtoReflect.Descriptor instead.
func (*Seiren) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_seiren_proto_rawDescGZIP(), []int{0}
}

func (x *Seiren) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Seiren) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Seiren) GetWindow() *SeirenWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Seiren) GetGaps() []*SeirenGap {
	if x != nil {
		return x.Gaps
	}
	return nil
}

func (x *Seiren) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

// SeirenWindow is the span of the result the seiren was computed over (D300).
//
// `truncated` is true when the connector returned only PART of what exists —
// Generate Context returns a session's LAST events — so "no login in these
// events" cannot read as "no login in this session".
type SeirenWindow struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FirstEventTime string                 `protobuf:"bytes,1,opt,name=first_event_time,json=firstEventTime,proto3" json:"first_event_time,omitempty"`
	LastEventTime  string                 `protobuf:"bytes,2,opt,name=last_event_time,json=lastEventTime,proto3" json:"last_event_time,omitempty"`
	Truncated      bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SeirenWindow) Reset() {
	*x = SeirenWindow{}
	mi := &file_sekizui_v1_seiren_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeirenWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeirenWindow) ProtoMessage() {}

func (x *SeirenWindow) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_seiren_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeirenWindow.ProtoReflect.Descriptor instead.
func (*SeirenWindow) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_seiren_proto_rawDescGZIP(), []int{1}
}

func (x *SeirenWindow) GetFirstEventTime() string {
	if x != nil {
		return x.FirstEventTime
	}
	return ""
}

func (x *SeirenWindow) GetLastEventTime() string {
	if x != nil {
		return x.LastEventTime
	}
	return ""
}

func (x *SeirenWindow) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

// SeirenGap is one key the seiren could not give in full, and why.
type SeirenGap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key the rule writes.
	Key  string        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Kind SeirenGapKind `protobuf:"varint,2,opt,name=kind,proto3,enum=sekizui.v1.SeirenGapKind" json:"kind,omitempty"`
	// Names the cause without its value: the lens and the path it withheld, or
	// how many items a limit kept of how many there were.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeirenGap) Reset() {
	*x = SeirenGap{}
	mi := &file_sekizui_v1_seiren_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeirenGap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeirenGap) ProtoMessage() {}

func (x *SeirenGap) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_seiren_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeirenGap.ProtoReflect.Descriptor instead.
func (*SeirenGap) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_seiren_proto_rawDescGZIP(), []int{2}
}

func (x *SeirenGap) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SeirenGap) GetKind() SeirenGapKind {
	if x != nil {
		return x.Kind
	}
	return SeirenGapKind_SEIREN_GAP_KIND_UNSPECIFIED
}

func (x *SeirenGap) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_sekizui_v1_seiren_proto protoreflect.FileDescriptor

const file_sekizui_v1_seiren_proto_rawDesc = "" +
	"\n" +
	"\x17sekizui/v1/seiren.proto\x12\n" +
	"sekizui.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xbe\x01\n" +
	"\x06Seiren\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value\x120\n" +
	"\x06window\x18\x03 \x01(\v2\x18.sekizui.v1.SeirenWindowR\x06window\x12)\n" +
	"\x04gaps\x18\x04 \x03(\v2\x15.sekizui.v1.SeirenGapR\x04gaps\x12\x14\n" +
	"\x05rules\x18\x05 \x03(\tR\x05rules\"~\n" +
	"\fSeirenWindow\x12(\n" +
	"\x10first_event_time\x18\x01 \x01(\tR\x0efirstEventTime\x12&\n" +
	"\x0flast_event_time\x18\x02 \x01(\tR\rlastEventTime\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"d\n" +
	"\tSeirenGap\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x19.sekizui.v1.SeirenGapKindR\x04kind\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*p\n" +
	"\rSeirenGapKind\x12\x1f\n" +
	"\x1bSEIREN_GAP_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSEIREN_GAP_KIND_UNAVAILABLE\x10\x01\x12\x1d\n" +
	"\x19SEIREN_GAP_KIND_TRUNCATED\x10\x02B\xa7\x01\n" +
	"\x0ecom.sekizui.v1B\vSeirenProtoP\x01Z?github.com/fullstorydev/sekizui/pkg/schema/sekizui/v1;sekizuiv1\xa2\x02\x03SXX\xaa\x02\n" +
	"Sekizui.V1\xca\x02\n" +
	"Sekizui\\V1\xe2\x02\x16Sekizui\\V1\\GPBMetadata\xea\x02\vSekizui::V1b\x06proto3"

var (
	file_sekizui_v1_seiren_proto_rawDescOnce sync.Once
	file_sekizui_v1_seiren_proto_rawDescData []byte
)

func file_sekizui_v1_seiren_proto_rawDescGZIP() []byte {
	file_sekizui_v1_seiren_proto_rawDescOnce.Do(func() {
		file_sekizui_v1_seiren_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sekizui_v1_seiren_proto_rawDesc), len(file_sekizui_v1_seiren_proto_rawDesc)))
	})
	return file_sekizui_v1_seiren_proto_rawDescData
}

var file_sekizui_v1_seiren_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sekizui_v1_seiren_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sekizui_v1_seiren_proto_goTypes = []any{
	(SeirenGapKind)(0),      // 0: sekizui.v1.SeirenGapKind
	(*Seiren)(nil),          // 1: sekizui.v1.Seiren
	(*SeirenWindow)(nil),    // 2: sekizui.v1.SeirenWindow
	(*SeirenGap)(nil),       // 3: sekizui.v1.SeirenGap
	(*structpb.Struct)(nil), // 4: google.protobuf.Struct
}
var file_sekizui_v1_seiren_proto_depIdxs = []int32{
	4, // 0: sekizui.v1.Seiren.value:type_name -> google.protobuf.Struct
	2, // 1: sekizui.v1.Seiren.window:type_name -> sekizui.v1.SeirenWindow
	3, // 2: sekizui.v1.Seiren.gaps:type_name -> sekizui.v1.SeirenGap
	0, // 3: sekizui.v1.SeirenGap.kind:type_name -> sekizui.v1.SeirenGapKind
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sekizui_v1_seiren_proto_init() }
func file_sekizui_v1_seiren_proto_init() {
	if File_sekizui_v1_seiren_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sekizui_v1_seiren_proto_rawDesc), len(file_sekizui_v1_seiren_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sekizui_v1_seiren_proto_goTypes,
		DependencyIndexes: file_sekizui_v1_seiren_proto_depIdxs,
		EnumInfos:         file_sekizui_v1_seiren_proto_enumTypes,
		MessageInfos:      file_sekizui_v1_seiren_proto_msgTypes,
	}.Build()
	File_sekizui_v1_seiren_proto = out.File
	file_sekizui_v1_seiren_proto_goTypes = nil
	file_sekizui_v1_seiren_proto_depIdxs = nil
}
