// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: sekizui/v1/service.proto

package sekizuiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_Execute_FullMethodName    = "/sekizui.v1.GatewayService/Execute"
	GatewayService_Query_FullMethodName      = "/sekizui.v1.GatewayService/Query"
	GatewayService_Subscribe_FullMethodName  = "/sekizui.v1.GatewayService/Subscribe"
	GatewayService_StartJob_FullMethodName   = "/sekizui.v1.GatewayService/StartJob"
	GatewayService_CancelJob_FullMethodName  = "/sekizui.v1.GatewayService/CancelJob"
	GatewayService_JobStatus_FullMethodName  = "/sekizui.v1.GatewayService/JobStatus"
	GatewayService_JobResults_FullMethodName = "/sekizui.v1.GatewayService/JobResults"
	GatewayService_Describe_FullMethodName   = "/sekizui.v1.GatewayService/Describe"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayService is the command/query/subscribe surface served by
// `sekizui-gateway` (§5.3). Named for the deployment rather than the product so
// that if `sekizui-ingest` ever exposes RPCs it becomes IngestService, keeping the
// deployment split visible in the API.
type GatewayServiceClient interface {
	// Execute one command against one target. The core governed pathway:
	// verify -> authorise -> resolve -> rate limit -> act -> audit.
	//
	// Reflexes call the same internal path. There is no fast lane (D18).
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	// Read-through query against a target. Governed identically to Execute —
	// an agent running an unbounded scan across BigQuery is a data-exfiltration
	// path, so reads carry the same capability checks plus result-size limits
	// (§4.1.1).
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Server-streaming event subscription.
	//
	// This is how anything outside the process receives the bus in v1.
	//
	// Delivery is AT-MOST-ONCE (D24), honestly: a dropped connection loses the
	// events sent during the gap. No acks, no cursors, no replay — because
	// pretending otherwise with an in-process bus behind it would be a lie.
	//
	// Forward compatibility: when JetStream lands (P7/v1.3) this RPC stays as a
	// facade and silently gains at-least-once plus replay. Consumers do not change.
	// If a consumer ever needs to know which delivery semantics it is getting, the
	// Bus abstraction has leaked and the interface is wrong (§4.6.4 item 3).
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
	// Start a governed asynchronous job.
	//
	// **A FOURTH PATTERN BECAUSE THE OTHER THREE CANNOT CARRY IT** (§4.1.1).
	// "Review five sessions for these behaviours" is too slow and too large for
	// a Query, whose result is one synchronous response; it is a READ, so it is
	// not a Command; and a Subscribe is a standing stream rather than something
	// with an end. What is missing is a request that has a caller, has a defined
	// end, and OUTLIVES THE CONNECTION THAT MADE IT.
	//
	// It carries a `Command` rather than a new vocabulary, because a job is a
	// governed action with a longer life and not a different kind of thing —
	// same action names, same grants, same ceilings. D18 forbids a second path
	// and this is deliberately not one.
	//
	// **A RECURRING JOB IS THIS WITH CONFIGURATION AS THE CALLER (D249).** The
	// scheduled trigger reaches the same runner through the same admission; a
	// poller is not a second subsystem.
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	// Cancel a running job, or a recurrence.
	//
	// **CANCELLING MUST STOP THE WORK, NOT JUST THE SUBSCRIPTION** (P3 criterion
	// 16). A caller who unsubscribes from a job that keeps running has bought
	// nothing: the credential it borrowed stays borrowed and the vendor keeps
	// being billed for output nobody will read.
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// How is my job going?
	//
	// **THE CALLER'S HALF OF P3 CRITERION 15, AND IT EXISTS BECAUSE THE AUDIT
	// RECORD IS NOT IT (D254).** The criterion asks that finished, failed and
	// still-running be distinguishable AND that a caller not have to infer the
	// answer from silence. The decision record answers the first for an
	// OPERATOR; there is no RPC that reads the audit log, so a caller holding a
	// `decision_id` could resolve nothing and a job whose end it could not see
	// is the melt in a different coat.
	//
	// **NOT A GRANT — A JOB IS YOUR OWN.** Authorisation is identity equality
	// with the principal recorded on the job's intent row, which is why this
	// verb takes no capability and appears in no catalog. A grant would be the
	// wrong instrument: it would let an operator write "may read jobs", which
	// means "may read ANYBODY's jobs", and there is no legitimate reading of
	// that a deployment would want.
	//
	// **AN UNKNOWN JOB AND SOMEBODY ELSE'S JOB ANSWER IDENTICALLY**, so this is
	// not an oracle for which job ids exist. The audit log tells the two apart
	// for whoever is accountable; the caller is told neither.
	JobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
	// What did my job produce?
	//
	// **A JOB'S RESULTS ARE ADDRESSED TO ITS CALLER, NOT PUBLISHED (D267).**
	// D247 put them on the shared bus, where every principal whose subscribe
	// grant matched received another principal's requested data — what it asked
	// for, and volume it chose — and where, once reflexes arm, a read-only caller
	// could trigger writes by starting jobs. They are buffered for this caller
	// instead, lensed per delivery as a subscription is.
	//
	// **ATTACH AFTER STARTING.** The results are held from the moment StartJob
	// returns, so the subscribe-before-start ordering at-most-once forced on a
	// bus reader (D24) does not apply. **THE STREAM ENDS WHEN THE JOB DOES** —
	// the end a bus subscription could never give — and JobStatus then says how.
	//
	// Authorised as JobStatus is, by identity equality with the job's owner: an
	// unknown job and somebody else's are answered identically (NOT_FOUND), and
	// the second is recorded. One reader per job; results nobody collects are
	// dropped ten minutes after the job ends, and the drop is logged.
	JobResults(ctx context.Context, in *JobResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobResultsResponse], error)
	// What may this principal do?
	//
	// Derived from the SAME grant data the enforcer reads (§4.9 property 1). A
	// separately maintained list would drift, and then agents get told about tools
	// that deny — burning turns and confusing the model.
	//
	// Two callers, two uses:
	//   - agents, at runtime: choose among available capabilities
	//   - reflex config loading, at boot: validate a fixed choice (§4.11.4b)
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, GatewayService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, GatewayService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

func (c *gatewayServiceClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartJobResponse)
	err := c.cc.Invoke(ctx, GatewayService_StartJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, GatewayService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) JobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, GatewayService_JobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) JobResults(ctx context.Context, in *JobResultsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobResultsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[1], GatewayService_JobResults_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JobResultsRequest, JobResultsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_JobResultsClient = grpc.ServerStreamingClient[JobResultsResponse]

func (c *gatewayServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, GatewayService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations should embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// GatewayService is the command/query/subscribe surface served by
// `sekizui-gateway` (§5.3). Named for the deployment rather than the product so
// that if `sekizui-ingest` ever exposes RPCs it becomes IngestService, keeping the
// deployment split visible in the API.
type GatewayServiceServer interface {
	// Execute one command against one target. The core governed pathway:
	// verify -> authorise -> resolve -> rate limit -> act -> audit.
	//
	// Reflexes call the same internal path. There is no fast lane (D18).
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	// Read-through query against a target. Governed identically to Execute —
	// an agent running an unbounded scan across BigQuery is a data-exfiltration
	// path, so reads carry the same capability checks plus result-size limits
	// (§4.1.1).
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Server-streaming event subscription.
	//
	// This is how anything outside the process receives the bus in v1.
	//
	// Delivery is AT-MOST-ONCE (D24), honestly: a dropped connection loses the
	// events sent during the gap. No acks, no cursors, no replay — because
	// pretending otherwise with an in-process bus behind it would be a lie.
	//
	// Forward compatibility: when JetStream lands (P7/v1.3) this RPC stays as a
	// facade and silently gains at-least-once plus replay. Consumers do not change.
	// If a consumer ever needs to know which delivery semantics it is getting, the
	// Bus abstraction has leaked and the interface is wrong (§4.6.4 item 3).
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	// Start a governed asynchronous job.
	//
	// **A FOURTH PATTERN BECAUSE THE OTHER THREE CANNOT CARRY IT** (§4.1.1).
	// "Review five sessions for these behaviours" is too slow and too large for
	// a Query, whose result is one synchronous response; it is a READ, so it is
	// not a Command; and a Subscribe is a standing stream rather than something
	// with an end. What is missing is a request that has a caller, has a defined
	// end, and OUTLIVES THE CONNECTION THAT MADE IT.
	//
	// It carries a `Command` rather than a new vocabulary, because a job is a
	// governed action with a longer life and not a different kind of thing —
	// same action names, same grants, same ceilings. D18 forbids a second path
	// and this is deliberately not one.
	//
	// **A RECURRING JOB IS THIS WITH CONFIGURATION AS THE CALLER (D249).** The
	// scheduled trigger reaches the same runner through the same admission; a
	// poller is not a second subsystem.
	StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error)
	// Cancel a running job, or a recurrence.
	//
	// **CANCELLING MUST STOP THE WORK, NOT JUST THE SUBSCRIPTION** (P3 criterion
	// 16). A caller who unsubscribes from a job that keeps running has bought
	// nothing: the credential it borrowed stays borrowed and the vendor keeps
	// being billed for output nobody will read.
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// How is my job going?
	//
	// **THE CALLER'S HALF OF P3 CRITERION 15, AND IT EXISTS BECAUSE THE AUDIT
	// RECORD IS NOT IT (D254).** The criterion asks that finished, failed and
	// still-running be distinguishable AND that a caller not have to infer the
	// answer from silence. The decision record answers the first for an
	// OPERATOR; there is no RPC that reads the audit log, so a caller holding a
	// `decision_id` could resolve nothing and a job whose end it could not see
	// is the melt in a different coat.
	//
	// **NOT A GRANT — A JOB IS YOUR OWN.** Authorisation is identity equality
	// with the principal recorded on the job's intent row, which is why this
	// verb takes no capability and appears in no catalog. A grant would be the
	// wrong instrument: it would let an operator write "may read jobs", which
	// means "may read ANYBODY's jobs", and there is no legitimate reading of
	// that a deployment would want.
	//
	// **AN UNKNOWN JOB AND SOMEBODY ELSE'S JOB ANSWER IDENTICALLY**, so this is
	// not an oracle for which job ids exist. The audit log tells the two apart
	// for whoever is accountable; the caller is told neither.
	JobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error)
	// What did my job produce?
	//
	// **A JOB'S RESULTS ARE ADDRESSED TO ITS CALLER, NOT PUBLISHED (D267).**
	// D247 put them on the shared bus, where every principal whose subscribe
	// grant matched received another principal's requested data — what it asked
	// for, and volume it chose — and where, once reflexes arm, a read-only caller
	// could trigger writes by starting jobs. They are buffered for this caller
	// instead, lensed per delivery as a subscription is.
	//
	// **ATTACH AFTER STARTING.** The results are held from the moment StartJob
	// returns, so the subscribe-before-start ordering at-most-once forced on a
	// bus reader (D24) does not apply. **THE STREAM ENDS WHEN THE JOB DOES** —
	// the end a bus subscription could never give — and JobStatus then says how.
	//
	// Authorised as JobStatus is, by identity equality with the job's owner: an
	// unknown job and somebody else's are answered identically (NOT_FOUND), and
	// the second is recorded. One reader per job; results nobody collects are
	// dropped ten minutes after the job ends, and the drop is logged.
	JobResults(*JobResultsRequest, grpc.ServerStreamingServer[JobResultsResponse]) error
	// What may this principal do?
	//
	// Derived from the SAME grant data the enforcer reads (§4.9 property 1). A
	// separately maintained list would drift, and then agents get told about tools
	// that deny — burning turns and confusing the model.
	//
	// Two callers, two uses:
	//   - agents, at runtime: choose among available capabilities
	//   - reflex config loading, at boot: validate a fixed choice (§4.11.4b)
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
}

// UnimplementedGatewayServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedGatewayServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedGatewayServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedGatewayServiceServer) StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedGatewayServiceServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedGatewayServiceServer) JobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobStatus not implemented")
}
func (UnimplementedGatewayServiceServer) JobResults(*JobResultsRequest, grpc.ServerStreamingServer[JobResultsResponse]) error {
	return status.Error(codes.Unimplemented, "method JobResults not implemented")
}
func (UnimplementedGatewayServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue() {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

func _GatewayService_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_StartJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).StartJob(ctx, req.(*StartJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_JobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).JobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_JobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).JobStatus(ctx, req.(*JobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_JobResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).JobResults(m, &grpc.GenericServerStream[JobResultsRequest, JobResultsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_JobResultsServer = grpc.ServerStreamingServer[JobResultsResponse]

func _GatewayService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sekizui.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _GatewayService_Execute_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _GatewayService_Query_Handler,
		},
		{
			MethodName: "StartJob",
			Handler:    _GatewayService_StartJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _GatewayService_CancelJob_Handler,
		},
		{
			MethodName: "JobStatus",
			Handler:    _GatewayService_JobStatus_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _GatewayService_Describe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _GatewayService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "JobResults",
			Handler:       _GatewayService_JobResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sekizui/v1/service.proto",
}
