// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sekizui/v1/service.proto

package sekizuiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobState is how a job is going, in the three states P3 criterion 15 requires
// be distinguishable.
type JobState int32

const (
	// Unknown: no such job, or not yours. **THE TWO ARE DELIBERATELY ONE
	// VALUE** — separating them would answer "does this job id exist" for a
	// caller with no business knowing, which is an enumeration oracle built out
	// of politeness.
	JobState_JOB_STATE_UNSPECIFIED JobState = 0
	JobState_JOB_STATE_RUNNING     JobState = 1
	// Finished, whether or not it produced anything. `events` is what makes a
	// job that found nothing legible as a success rather than as a silence.
	JobState_JOB_STATE_FINISHED JobState = 2
	JobState_JOB_STATE_FAILED   JobState = 3
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_RUNNING",
		2: "JOB_STATE_FINISHED",
		3: "JOB_STATE_FAILED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED": 0,
		"JOB_STATE_RUNNING":     1,
		"JOB_STATE_FINISHED":    2,
		"JOB_STATE_FAILED":      3,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_service_proto_enumTypes[0].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_sekizui_v1_service_proto_enumTypes[0]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{0}
}

// CancelScope distinguishes this run from every future one.
type CancelScope int32

const (
	// Unspecified is treated as THIS_RUN — the narrower action, because the
	// safe reading of an ambiguous cancellation is the one that stops less and
	// can be repeated, not the one that silently ends a schedule.
	CancelScope_CANCEL_SCOPE_UNSPECIFIED CancelScope = 0
	// Stop the run in flight. A recurrence continues.
	CancelScope_CANCEL_SCOPE_THIS_RUN CancelScope = 1
	// Stop the run in flight AND the recurrence. Meaningless for a one-shot
	// job, and refused there rather than silently equivalent.
	CancelScope_CANCEL_SCOPE_RECURRENCE CancelScope = 2
)

// Enum value maps for CancelScope.
var (
	CancelScope_name = map[int32]string{
		0: "CANCEL_SCOPE_UNSPECIFIED",
		1: "CANCEL_SCOPE_THIS_RUN",
		2: "CANCEL_SCOPE_RECURRENCE",
	}
	CancelScope_value = map[string]int32{
		"CANCEL_SCOPE_UNSPECIFIED": 0,
		"CANCEL_SCOPE_THIS_RUN":    1,
		"CANCEL_SCOPE_RECURRENCE":  2,
	}
)

func (x CancelScope) Enum() *CancelScope {
	p := new(CancelScope)
	*p = x
	return p
}

func (x CancelScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CancelScope) Descriptor() protoreflect.EnumDescriptor {
	return file_sekizui_v1_service_proto_enumTypes[1].Descriptor()
}

func (CancelScope) Type() protoreflect.EnumType {
	return &file_sekizui_v1_service_proto_enumTypes[1]
}

func (x CancelScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CancelScope.Descriptor instead.
func (CancelScope) EnumDescriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{1}
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_sekizui_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *CommandResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_sekizui_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetResult() *CommandResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "jira.search", "bigquery.query", "fullstory.get_session".
	Action    string           `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	TargetRef string           `protobuf:"bytes,2,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	Args      *structpb.Struct `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	// Caller-requested cap. The effective limit is min(this, granted max_results),
	// so a caller can ask for less but never for more.
	MaxResults uint32 `protobuf:"varint,4,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	// Opaque continuation token from a previous QueryResponse.
	PageToken string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Shin lens this consumer selects for itself (D84).
	//
	// SELECTED BY NAME, NEVER COMPOSED. A consumer chooses among lenses an operator
	// declared and reviewed — the same model D46 uses for MCP tools, for the same
	// reason: what is not declared is not selectable. Naming an unknown or
	// non-requestable lens is REFUSED rather than ignored.
	//
	// The imposed ceiling applies regardless, and a selection can only narrow
	// further. There is no value here that widens what arrives.
	Lens          string `protobuf:"bytes,6,opt,name=lens,proto3" json:"lens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_sekizui_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *QueryRequest) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *QueryRequest) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *QueryRequest) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *QueryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *QueryRequest) GetLens() string {
	if x != nil {
		return x.Lens
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=sekizui.v1.Status" json:"status,omitempty"`
	Rows          []*structpb.Struct     `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	NextPageToken string                 `protobuf:"bytes,4,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// True when results were cut short by a granted limit rather than exhausted.
	//
	// Explicit because a silently truncated result set reads as a complete one, and
	// an agent reasoning over a truncated set will reach confident wrong
	// conclusions.
	Truncated bool   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Reason    string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// Names every shin lens that shaped these rows, imposed and selected alike.
	//
	// REPORTED, NOT SILENT. A consumer that receives four fields where it expected
	// nine must be able to tell "a lens removed them" from "the data was not
	// there" — and an operator debugging a support ticket needs to know WHICH lens
	// without reading config.
	AppliedLenses []string `protobuf:"bytes,7,rep,name=applied_lenses,json=appliedLenses,proto3" json:"applied_lenses,omitempty"`
	// WHICH STAGE refused this read, when it was refused (D135, D155).
	//
	// `CommandResult` has carried this since D135 and `QueryResponse` did not,
	// which is the same asymmetry D155 is about: reads were governed by fewer
	// stages AND could not say which one refused them. §4.1.1's rule is that the
	// two planes are "distinguishable in policy and audit, not differently
	// governed", and a caller told only STATUS_DENIED about a read cannot tell a
	// missing grant from a suspended principal from an anzen rule from a
	// credential somebody revoked twenty minutes ago.
	//
	// Unspecified on an allowed read.
	RefusedBy RefusedBy `protobuf:"varint,8,opt,name=refused_by,json=refusedBy,proto3,enum=sekizui.v1.RefusedBy" json:"refused_by,omitempty"`
	// The SEIREN (精錬) beside the rows: what the `refines:` rules imposed on this
	// caller made of the WHOLE result, before any paging or response budget
	// (D297, D300, D317). Absent when no rule is imposed. `rows` stay silver.
	Seiren        *Seiren `protobuf:"bytes,9,opt,name=seiren,proto3" json:"seiren,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_sekizui_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *QueryResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *QueryResponse) GetRows() []*structpb.Struct {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *QueryResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *QueryResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *QueryResponse) GetAppliedLenses() []string {
	if x != nil {
		return x.AppliedLenses
	}
	return nil
}

func (x *QueryResponse) GetRefusedBy() RefusedBy {
	if x != nil {
		return x.RefusedBy
	}
	return RefusedBy_REFUSED_BY_UNSPECIFIED
}

func (x *QueryResponse) GetSeiren() *Seiren {
	if x != nil {
		return x.Seiren
	}
	return nil
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject filters, e.g. ["sekizui.enriched.>", "sekizui.raw.jira.>"].
	// Empty means everything the principal is granted.
	//
	// Stage prefixes are configured, not fixed (D43).
	Subjects []string `protobuf:"bytes,1,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Optional payload type filter, e.g. ["fullstory.rage_click.v1"].
	Types []string `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	// Optional residency filter. A consumer in a US region can decline
	// EU-resident envelopes rather than receiving and then having to drop them.
	Residency string `protobuf:"bytes,3,opt,name=residency,proto3" json:"residency,omitempty"`
	// Include the projection field when present (§4.6.2). Off by default because
	// projections cost bytes that stream consumers may not want.
	IncludeProjection bool `protobuf:"varint,4,opt,name=include_projection,json=includeProjection,proto3" json:"include_projection,omitempty"`
	// Shin lens this consumer selects for its deliveries (D84).
	//
	// Same rule as QueryRequest.lens: selected by name from lenses an operator
	// declared, never composed per request. The imposed ceiling applies to every
	// envelope regardless, and a selection can only narrow further.
	Lens          string `protobuf:"bytes,5,opt,name=lens,proto3" json:"lens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_sekizui_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *SubscribeRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *SubscribeRequest) GetResidency() string {
	if x != nil {
		return x.Residency
	}
	return ""
}

func (x *SubscribeRequest) GetIncludeProjection() bool {
	if x != nil {
		return x.IncludeProjection
	}
	return false
}

func (x *SubscribeRequest) GetLens() string {
	if x != nil {
		return x.Lens
	}
	return ""
}

// SubscribeResponse wraps each streamed envelope.
//
// The wrapper is not ceremony. Under at-most-once (D24) a consumer otherwise has
// NO WAY to learn that it missed events — silent loss is the worst property of
// the v1 bus. This makes loss VISIBLE, which is the honest thing to offer instead
// of reliability we do not have. It also leaves room for stream-level signals to
// be added without breaking consumers.
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset on a heartbeat.
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Keepalive. Lets a consumer distinguish "idle" from "connection dead" without
	// a separate mechanism.
	Heartbeat bool `protobuf:"varint,2,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	// Best-effort count of envelopes dropped for this subscription since the last
	// message — slow consumer, or bounded-buffer overflow.
	//
	// Does not make delivery reliable. Makes it auditable.
	Dropped uint64 `protobuf:"varint,3,opt,name=dropped,proto3" json:"dropped,omitempty"`
	// Reserved for the JetStream upgrade (P7): opaque position a consumer may
	// present to resume. Always empty under at-most-once, which is exactly why
	// consumers should read it now and get resumption for free later.
	ResumeToken   string `protobuf:"bytes,4,opt,name=resume_token,json=resumeToken,proto3" json:"resume_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_sekizui_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *SubscribeResponse) GetHeartbeat() bool {
	if x != nil {
		return x.Heartbeat
	}
	return false
}

func (x *SubscribeResponse) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *SubscribeResponse) GetResumeToken() string {
	if x != nil {
		return x.ResumeToken
	}
	return ""
}

type DescribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Principal to describe. Empty means the effective identity of this request —
	// the common case for an agent asking "what can I do?".
	//
	// Naming another principal requires a grant to do so; otherwise an agent could
	// enumerate the whole fleet's permissions.
	Principal     string `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_sekizui_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeRequest) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

type DescribeResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Principal string                 `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	// Effective capability set: intersection of caller and subject grants (D7),
	// with constraints inlined into each description for LLM consumption.
	Capabilities []*Capability `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Principals this one may act on behalf of (§4.4.1). Empty for leaf principals
	// such as agents and reflexes.
	MaySpeakFor []string `protobuf:"bytes,3,rep,name=may_speak_for,json=maySpeakFor,proto3" json:"may_speak_for,omitempty"`
	// Registered payload schemas visible to this principal, as
	// type -> schema URI. Lets a consumer fetch the shape of what it will receive
	// (D40) rather than inferring it from examples.
	PayloadSchemas map[string]string `protobuf:"bytes,4,rep,name=payload_schemas,json=payloadSchemas,proto3" json:"payload_schemas,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Shin lenses this principal may SELECT (D84). Selecting one narrows further;
	// none of them can widen what arrives.
	AvailableLenses []*LensInfo `protobuf:"bytes,5,rep,name=available_lenses,json=availableLenses,proto3" json:"available_lenses,omitempty"`
	// The imposed ceiling in force for this principal — lenses it cannot decline.
	//
	// REPORTED, NOT HIDDEN. A consumer that cannot see its own ceiling will keep
	// asking why a field never arrives, and the honest answer is in configuration
	// somebody else wrote. Naming the lens and its rationale turns a mystery into
	// a conversation with a named owner.
	ImposedLenses []*LensInfo `protobuf:"bytes,6,rep,name=imposed_lenses,json=imposedLenses,proto3" json:"imposed_lenses,omitempty"`
	// Capabilities an anzen guard WITHHELD, with the rule that withheld each.
	//
	// **AN ABSENCE WITH NO EXPLANATION IS THE DEFECT THIS FIXES (CONTRACTS 64).**
	// `anzen.Guards.Forbids` returns the guard's name and the catalog discarded it
	// with `_`, so an agent saw a capability simply missing — indistinguishable
	// from one it was never granted, and unanswerable without reading
	// configuration somebody else wrote. Naming the rule is §5.4's argument about
	// refusals ("a denial that records *why* is what makes the system reviewable
	// rather than merely restrictive") applied to the catalog, and it is the same
	// reasoning `imposed_lenses` above already carries for shin.
	//
	// **IT DISCLOSES THE RULE'S NAME AND NOTHING ELSE.** Not its patterns, not its
	// severity, not what else it forbids: the caller learns why THIS capability is
	// absent for THEM — which is what stops them asking — and a name is something
	// to take to whoever owns the guard. A guard is a ceiling no grant can exceed
	// (D71), so this is not a grant to widen.
	Withheld []*WithheldCapability `protobuf:"bytes,7,rep,name=withheld,proto3" json:"withheld,omitempty"`
	// Every refinement imposed on this principal, from the same compiled list
	// the gateway serves (D302) — so discovery cannot advertise a seiren that
	// does not arrive, or omit one that does. Empty when none is imposed.
	ImposedRefinements []*ImposedRefinement `protobuf:"bytes,8,rep,name=imposed_refinements,json=imposedRefinements,proto3" json:"imposed_refinements,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_sekizui_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *DescribeResponse) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *DescribeResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DescribeResponse) GetMaySpeakFor() []string {
	if x != nil {
		return x.MaySpeakFor
	}
	return nil
}

func (x *DescribeResponse) GetPayloadSchemas() map[string]string {
	if x != nil {
		return x.PayloadSchemas
	}
	return nil
}

func (x *DescribeResponse) GetAvailableLenses() []*LensInfo {
	if x != nil {
		return x.AvailableLenses
	}
	return nil
}

func (x *DescribeResponse) GetImposedLenses() []*LensInfo {
	if x != nil {
		return x.ImposedLenses
	}
	return nil
}

func (x *DescribeResponse) GetWithheld() []*WithheldCapability {
	if x != nil {
		return x.Withheld
	}
	return nil
}

func (x *DescribeResponse) GetImposedRefinements() []*ImposedRefinement {
	if x != nil {
		return x.ImposedRefinements
	}
	return nil
}

// WithheldCapability is one capability an anzen guard kept out of the catalog.
// ImposedRefinement is one `refines:` rule imposed on the described principal
// (D298, D302): configuration decides it, so discovery must say it — a seiren
// never arrives undeclared.
type ImposedRefinement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The connector's rule, e.g. "fullstory.login".
	Rule string `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	// The target whose results it refines.
	TargetRef string `protobuf:"bytes,2,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	// The seiren type it writes, and where its schema is fetched (D40).
	SeirenType string `protobuf:"bytes,3,opt,name=seiren_type,json=seirenType,proto3" json:"seiren_type,omitempty"`
	SchemaUri  string `protobuf:"bytes,4,opt,name=schema_uri,json=schemaUri,proto3" json:"schema_uri,omitempty"`
	// The one key of that type it writes.
	Key string `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	// Whether it looks anything up — spending the caller's quota (D298). Always
	// false in P4, whose engine only derives (D317); P5's lookups set it.
	Lookups       bool `protobuf:"varint,6,opt,name=lookups,proto3" json:"lookups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImposedRefinement) Reset() {
	*x = ImposedRefinement{}
	mi := &file_sekizui_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImposedRefinement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImposedRefinement) ProtoMessage() {}

func (x *ImposedRefinement) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImposedRefinement.ProtoReflect.Descriptor instead.
func (*ImposedRefinement) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *ImposedRefinement) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *ImposedRefinement) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *ImposedRefinement) GetSeirenType() string {
	if x != nil {
		return x.SeirenType
	}
	return ""
}

func (x *ImposedRefinement) GetSchemaUri() string {
	if x != nil {
		return x.SchemaUri
	}
	return ""
}

func (x *ImposedRefinement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ImposedRefinement) GetLookups() bool {
	if x != nil {
		return x.Lookups
	}
	return false
}

type WithheldCapability struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Action    string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	TargetRef string                 `protobuf:"bytes,2,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	// The anzen rule that withheld it.
	Guard         string `protobuf:"bytes,3,opt,name=guard,proto3" json:"guard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithheldCapability) Reset() {
	*x = WithheldCapability{}
	mi := &file_sekizui_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithheldCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithheldCapability) ProtoMessage() {}

func (x *WithheldCapability) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithheldCapability.ProtoReflect.Descriptor instead.
func (*WithheldCapability) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *WithheldCapability) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WithheldCapability) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *WithheldCapability) GetGuard() string {
	if x != nil {
		return x.Guard
	}
	return ""
}

// LensInfo describes one shin lens to a consumer.
type LensInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Payload type this lens applies to, or empty for every type.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Field allow-list. Empty means every field survives, subject to withholds.
	Fields []string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Fields removed unconditionally. Wins over `fields`.
	Withholds []string `protobuf:"bytes,4,rep,name=withholds,proto3" json:"withholds,omitempty"`
	// Cap on ONE payload's serialised size. Not a rate limit (§4.3.4).
	MaxBytes uint32 `protobuf:"varint,5,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	// Why this lens exists. REQUIRED in configuration, because a lens removes
	// data and "why does this consumer never see that field" must be answerable
	// without finding whoever wrote it.
	Because       string `protobuf:"bytes,6,opt,name=because,proto3" json:"because,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LensInfo) Reset() {
	*x = LensInfo{}
	mi := &file_sekizui_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LensInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LensInfo) ProtoMessage() {}

func (x *LensInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LensInfo.ProtoReflect.Descriptor instead.
func (*LensInfo) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *LensInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LensInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LensInfo) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LensInfo) GetWithholds() []string {
	if x != nil {
		return x.Withholds
	}
	return nil
}

func (x *LensInfo) GetMaxBytes() uint32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *LensInfo) GetBecause() string {
	if x != nil {
		return x.Because
	}
	return ""
}

type StartJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The action, target and arguments, exactly as Execute takes them.
	Command       *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_sekizui_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *StartJobRequest) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type StartJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The job's identifier, and **ALSO THE CAUSATION ROOT OF EVERY ENVELOPE IT
	// PRODUCES** — which is why no new envelope field was added for it.
	//
	// `Causation.root_id` already means "the originating thing at the root of
	// this chain", and for a job that is the job. A caller subscribes and
	// filters on the root; a polled event, which has no such origin, remains
	// its own root (see internal/translate). One field, two honest readings,
	// rather than a `job_id` extension attribute that would mean nothing on
	// three quarters of the envelopes carrying it.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// The decision that admitted it, so a caller can cite the row that says
	// why they were allowed to start it (D201).
	//
	// POPULATED ON A REFUSAL TOO, which is the half that matters: a caller told
	// only that no job started cannot cite the row that says why.
	DecisionId string `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	// The outcome of ASKING, which is not the outcome of the job (D250).
	//
	// **AN EMPTY `job_id` IS A NEGATIVE ASSERTION, AND THIS REPOSITORY HAS
	// ALREADY PAID FOR ONE.** D138 found `STATUS_INVALID_ARGUMENT` missing
	// because an acceptance assertion written as `!= STATUS_OK` was satisfied by
	// the absence of an answer; "no job id came back" is the same shape. So a
	// refusal says so positively, and D135's rule — a deliberate refusal is a
	// result with a mapped status rather than a transport error — reaches this
	// verb as it reaches the other two.
	Status Status `protobuf:"varint,3,opt,name=status,proto3,enum=sekizui.v1.Status" json:"status,omitempty"`
	// Why, in words an operator can act on. Empty when a job started.
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// WHICH STAGE refused it (D135, D155).
	//
	// `QueryResponse` gained this for exactly this reason and the argument
	// transfers unchanged: a caller told only STATUS_DENIED cannot tell a
	// missing grant from a suspended principal from an anzen rule from a
	// credential somebody revoked twenty minutes ago. **A JOB MAKES IT WORSE
	// RATHER THAN EQUAL**, because the window between authorisation and use is
	// the widest in the system (P3 criterion 17) — so the stage that refused is
	// the caller's only clue about whether asking again in a minute could
	// possibly work.
	//
	// Unspecified when a job started.
	RefusedBy     RefusedBy `protobuf:"varint,5,opt,name=refused_by,json=refusedBy,proto3,enum=sekizui.v1.RefusedBy" json:"refused_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_sekizui_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *StartJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StartJobResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *StartJobResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *StartJobResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StartJobResponse) GetRefusedBy() RefusedBy {
	if x != nil {
		return x.RefusedBy
	}
	return RefusedBy_REFUSED_BY_UNSPECIFIED
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_sekizui_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobResultsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Shin lens this caller selects for its results (D84) — the same rule as
	// SubscribeRequest.lens: chosen by name from lenses an operator declared,
	// never composed per request, and only ever narrowing the imposed ceiling.
	Lens string `protobuf:"bytes,2,opt,name=lens,proto3" json:"lens,omitempty"`
	// Include the projection when one applies (§4.6.2, D269) — as
	// SubscribeRequest.include_projection. Off by default: a projection costs
	// bytes a caller may not want, and it is shaped only for a caller who asked.
	IncludeProjection bool `protobuf:"varint,3,opt,name=include_projection,json=includeProjection,proto3" json:"include_projection,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JobResultsRequest) Reset() {
	*x = JobResultsRequest{}
	mi := &file_sekizui_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResultsRequest) ProtoMessage() {}

func (x *JobResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResultsRequest.ProtoReflect.Descriptor instead.
func (*JobResultsRequest) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *JobResultsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResultsRequest) GetLens() string {
	if x != nil {
		return x.Lens
	}
	return ""
}

func (x *JobResultsRequest) GetIncludeProjection() bool {
	if x != nil {
		return x.IncludeProjection
	}
	return false
}

// JobResultsResponse wraps one result, as SubscribeResponse wraps a delivery.
type JobResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *Envelope              `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResultsResponse) Reset() {
	*x = JobResultsResponse{}
	mi := &file_sekizui_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResultsResponse) ProtoMessage() {}

func (x *JobResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResultsResponse.ProtoReflect.Descriptor instead.
func (*JobResultsResponse) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *JobResultsResponse) GetEnvelope() *Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type JobStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	State JobState               `protobuf:"varint,1,opt,name=state,proto3,enum=sekizui.v1.JobState" json:"state,omitempty"`
	// How many envelopes reached the bus. Meaningful on a FAILED job too: one
	// that published four and then fell over published four (D177).
	Events int32 `protobuf:"varint,2,opt,name=events,proto3" json:"events,omitempty"`
	// The decision that admitted the job, so a caller can cite the row. Empty
	// when the state is UNSPECIFIED, which is the same answer for an unknown
	// job and somebody else's.
	DecisionId string `protobuf:"bytes,3,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	// Why it failed, in words the caller can act on. Empty otherwise.
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_sekizui_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *JobStatusResponse) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

func (x *JobStatusResponse) GetEvents() int32 {
	if x != nil {
		return x.Events
	}
	return 0
}

func (x *JobStatusResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *JobStatusResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// REQUIRED. A cancellation with no reason is an unexplained stop, and the
	// next person to look at the audit log is the one who pays for that —
	// the same rule D146 applies to suspending a grant.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// What to cancel. **THE DISTINCTION IS LOAD-BEARING FOR A RECURRENCE
	// (D249)**: an operator who meant to stop the schedule and stopped only the
	// run in flight has stopped nothing, and will believe otherwise until the
	// next tick.
	Scope         CancelScope `protobuf:"varint,3,opt,name=scope,proto3,enum=sekizui.v1.CancelScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_sekizui_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJobRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelJobRequest) GetScope() CancelScope {
	if x != nil {
		return x.Scope
	}
	return CancelScope_CANCEL_SCOPE_UNSPECIFIED
}

type CancelJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// False when there was nothing to cancel — a job already finished, or an id
	// nobody minted. NOT an error: "it already stopped" is the outcome the
	// caller wanted, and reporting it as a failure invites a retry loop.
	Cancelled bool `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	// What happened, in words an operator can act on.
	Detail        string `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_sekizui_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sekizui_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_sekizui_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *CancelJobResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

func (x *CancelJobResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_sekizui_v1_service_proto protoreflect.FileDescriptor

const file_sekizui_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18sekizui/v1/service.proto\x12\n" +
	"sekizui.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18sekizui/v1/command.proto\x1a\x15sekizui/v1/core.proto\x1a\x19sekizui/v1/decision.proto\x1a\x19sekizui/v1/envelope.proto\x1a\x17sekizui/v1/seiren.proto\"?\n" +
	"\x0eExecuteRequest\x12-\n" +
	"\acommand\x18\x01 \x01(\v2\x13.sekizui.v1.CommandR\acommand\"D\n" +
	"\x0fExecuteResponse\x121\n" +
	"\x06result\x18\x01 \x01(\v2\x19.sekizui.v1.CommandResultR\x06result\"\xc6\x01\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x02 \x01(\tR\ttargetRef\x12+\n" +
	"\x04args\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04args\x12\x1f\n" +
	"\vmax_results\x18\x04 \x01(\rR\n" +
	"maxResults\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12\x12\n" +
	"\x04lens\x18\x06 \x01(\tR\x04lens\"\xf0\x02\n" +
	"\rQueryResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.sekizui.v1.StatusR\x06status\x12+\n" +
	"\x04rows\x18\x03 \x03(\v2\x17.google.protobuf.StructR\x04rows\x12&\n" +
	"\x0fnext_page_token\x18\x04 \x01(\tR\rnextPageToken\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12%\n" +
	"\x0eapplied_lenses\x18\a \x03(\tR\rappliedLenses\x124\n" +
	"\n" +
	"refused_by\x18\b \x01(\x0e2\x15.sekizui.v1.RefusedByR\trefusedBy\x12*\n" +
	"\x06seiren\x18\t \x01(\v2\x12.sekizui.v1.SeirenR\x06seiren\"\xa5\x01\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bsubjects\x18\x01 \x03(\tR\bsubjects\x12\x14\n" +
	"\x05types\x18\x02 \x03(\tR\x05types\x12\x1c\n" +
	"\tresidency\x18\x03 \x01(\tR\tresidency\x12-\n" +
	"\x12include_projection\x18\x04 \x01(\bR\x11includeProjection\x12\x12\n" +
	"\x04lens\x18\x05 \x01(\tR\x04lens\"\xa0\x01\n" +
	"\x11SubscribeResponse\x120\n" +
	"\benvelope\x18\x01 \x01(\v2\x14.sekizui.v1.EnvelopeR\benvelope\x12\x1c\n" +
	"\theartbeat\x18\x02 \x01(\bR\theartbeat\x12\x18\n" +
	"\adropped\x18\x03 \x01(\x04R\adropped\x12!\n" +
	"\fresume_token\x18\x04 \x01(\tR\vresumeToken\"/\n" +
	"\x0fDescribeRequest\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\"\xb8\x04\n" +
	"\x10DescribeResponse\x12\x1c\n" +
	"\tprincipal\x18\x01 \x01(\tR\tprincipal\x12:\n" +
	"\fcapabilities\x18\x02 \x03(\v2\x16.sekizui.v1.CapabilityR\fcapabilities\x12\"\n" +
	"\rmay_speak_for\x18\x03 \x03(\tR\vmaySpeakFor\x12Y\n" +
	"\x0fpayload_schemas\x18\x04 \x03(\v20.sekizui.v1.DescribeResponse.PayloadSchemasEntryR\x0epayloadSchemas\x12?\n" +
	"\x10available_lenses\x18\x05 \x03(\v2\x14.sekizui.v1.LensInfoR\x0favailableLenses\x12;\n" +
	"\x0eimposed_lenses\x18\x06 \x03(\v2\x14.sekizui.v1.LensInfoR\rimposedLenses\x12:\n" +
	"\bwithheld\x18\a \x03(\v2\x1e.sekizui.v1.WithheldCapabilityR\bwithheld\x12N\n" +
	"\x13imposed_refinements\x18\b \x03(\v2\x1d.sekizui.v1.ImposedRefinementR\x12imposedRefinements\x1aA\n" +
	"\x13PayloadSchemasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x11ImposedRefinement\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x02 \x01(\tR\ttargetRef\x12\x1f\n" +
	"\vseiren_type\x18\x03 \x01(\tR\n" +
	"seirenType\x12\x1d\n" +
	"\n" +
	"schema_uri\x18\x04 \x01(\tR\tschemaUri\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x18\n" +
	"\alookups\x18\x06 \x01(\bR\alookups\"a\n" +
	"\x12WithheldCapability\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x02 \x01(\tR\ttargetRef\x12\x14\n" +
	"\x05guard\x18\x03 \x01(\tR\x05guard\"\x9f\x01\n" +
	"\bLensInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\x12\x1c\n" +
	"\twithholds\x18\x04 \x03(\tR\twithholds\x12\x1b\n" +
	"\tmax_bytes\x18\x05 \x01(\rR\bmaxBytes\x12\x18\n" +
	"\abecause\x18\x06 \x01(\tR\abecause\"@\n" +
	"\x0fStartJobRequest\x12-\n" +
	"\acommand\x18\x01 \x01(\v2\x13.sekizui.v1.CommandR\acommand\"\xc4\x01\n" +
	"\x10StartJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.sekizui.v1.StatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x124\n" +
	"\n" +
	"refused_by\x18\x05 \x01(\x0e2\x15.sekizui.v1.RefusedByR\trefusedBy\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"m\n" +
	"\x11JobResultsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04lens\x18\x02 \x01(\tR\x04lens\x12-\n" +
	"\x12include_projection\x18\x03 \x01(\bR\x11includeProjection\"F\n" +
	"\x12JobResultsResponse\x120\n" +
	"\benvelope\x18\x01 \x01(\v2\x14.sekizui.v1.EnvelopeR\benvelope\"\x90\x01\n" +
	"\x11JobStatusResponse\x12*\n" +
	"\x05state\x18\x01 \x01(\x0e2\x14.sekizui.v1.JobStateR\x05state\x12\x16\n" +
	"\x06events\x18\x02 \x01(\x05R\x06events\x12\x1f\n" +
	"\vdecision_id\x18\x03 \x01(\tR\n" +
	"decisionId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"p\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12-\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x17.sekizui.v1.CancelScopeR\x05scope\"I\n" +
	"\x11CancelJobResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail*j\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x01\x12\x16\n" +
	"\x12JOB_STATE_FINISHED\x10\x02\x12\x14\n" +
	"\x10JOB_STATE_FAILED\x10\x03*c\n" +
	"\vCancelScope\x12\x1c\n" +
	"\x18CANCEL_SCOPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CANCEL_SCOPE_THIS_RUN\x10\x01\x12\x1b\n" +
	"\x17CANCEL_SCOPE_RECURRENCE\x10\x022\xcf\x04\n" +
	"\x0eGatewayService\x12B\n" +
	"\aExecute\x12\x1a.sekizui.v1.ExecuteRequest\x1a\x1b.sekizui.v1.ExecuteResponse\x12<\n" +
	"\x05Query\x12\x18.sekizui.v1.QueryRequest\x1a\x19.sekizui.v1.QueryResponse\x12J\n" +
	"\tSubscribe\x12\x1c.sekizui.v1.SubscribeRequest\x1a\x1d.sekizui.v1.SubscribeResponse0\x01\x12E\n" +
	"\bStartJob\x12\x1b.sekizui.v1.StartJobRequest\x1a\x1c.sekizui.v1.StartJobResponse\x12H\n" +
	"\tCancelJob\x12\x1c.sekizui.v1.CancelJobRequest\x1a\x1d.sekizui.v1.CancelJobResponse\x12H\n" +
	"\tJobStatus\x12\x1c.sekizui.v1.JobStatusRequest\x1a\x1d.sekizui.v1.JobStatusResponse\x12M\n" +
	"\n" +
	"JobResults\x12\x1d.sekizui.v1.JobResultsRequest\x1a\x1e.sekizui.v1.JobResultsResponse0\x01\x12E\n" +
	"\bDescribe\x12\x1b.sekizui.v1.DescribeRequest\x1a\x1c.sekizui.v1.DescribeResponseB\xa8\x01\n" +
	"\x0ecom.sekizui.v1B\fServiceProtoP\x01Z?github.com/fullstorydev/sekizui/pkg/schema/sekizui/v1;sekizuiv1\xa2\x02\x03SXX\xaa\x02\n" +
	"Sekizui.V1\xca\x02\n" +
	"Sekizui\\V1\xe2\x02\x16Sekizui\\V1\\GPBMetadata\xea\x02\vSekizui::V1b\x06proto3"

var (
	file_sekizui_v1_service_proto_rawDescOnce sync.Once
	file_sekizui_v1_service_proto_rawDescData []byte
)

func file_sekizui_v1_service_proto_rawDescGZIP() []byte {
	file_sekizui_v1_service_proto_rawDescOnce.Do(func() {
		file_sekizui_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sekizui_v1_service_proto_rawDesc), len(file_sekizui_v1_service_proto_rawDesc)))
	})
	return file_sekizui_v1_service_proto_rawDescData
}

var file_sekizui_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sekizui_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_sekizui_v1_service_proto_goTypes = []any{
	(JobState)(0),              // 0: sekizui.v1.JobState
	(CancelScope)(0),           // 1: sekizui.v1.CancelScope
	(*ExecuteRequest)(nil),     // 2: sekizui.v1.ExecuteRequest
	(*ExecuteResponse)(nil),    // 3: sekizui.v1.ExecuteResponse
	(*QueryRequest)(nil),       // 4: sekizui.v1.QueryRequest
	(*QueryResponse)(nil),      // 5: sekizui.v1.QueryResponse
	(*SubscribeRequest)(nil),   // 6: sekizui.v1.SubscribeRequest
	(*SubscribeResponse)(nil),  // 7: sekizui.v1.SubscribeResponse
	(*DescribeRequest)(nil),    // 8: sekizui.v1.DescribeRequest
	(*DescribeResponse)(nil),   // 9: sekizui.v1.DescribeResponse
	(*ImposedRefinement)(nil),  // 10: sekizui.v1.ImposedRefinement
	(*WithheldCapability)(nil), // 11: sekizui.v1.WithheldCapability
	(*LensInfo)(nil),           // 12: sekizui.v1.LensInfo
	(*StartJobRequest)(nil),    // 13: sekizui.v1.StartJobRequest
	(*StartJobResponse)(nil),   // 14: sekizui.v1.StartJobResponse
	(*JobStatusRequest)(nil),   // 15: sekizui.v1.JobStatusRequest
	(*JobResultsRequest)(nil),  // 16: sekizui.v1.JobResultsRequest
	(*JobResultsResponse)(nil), // 17: sekizui.v1.JobResultsResponse
	(*JobStatusResponse)(nil),  // 18: sekizui.v1.JobStatusResponse
	(*CancelJobRequest)(nil),   // 19: sekizui.v1.CancelJobRequest
	(*CancelJobResponse)(nil),  // 20: sekizui.v1.CancelJobResponse
	nil,                        // 21: sekizui.v1.DescribeResponse.PayloadSchemasEntry
	(*Command)(nil),            // 22: sekizui.v1.Command
	(*CommandResult)(nil),      // 23: sekizui.v1.CommandResult
	(*structpb.Struct)(nil),    // 24: google.protobuf.Struct
	(Status)(0),                // 25: sekizui.v1.Status
	(RefusedBy)(0),             // 26: sekizui.v1.RefusedBy
	(*Seiren)(nil),             // 27: sekizui.v1.Seiren
	(*Envelope)(nil),           // 28: sekizui.v1.Envelope
	(*Capability)(nil),         // 29: sekizui.v1.Capability
}
var file_sekizui_v1_service_proto_depIdxs = []int32{
	22, // 0: sekizui.v1.ExecuteRequest.command:type_name -> sekizui.v1.Command
	23, // 1: sekizui.v1.ExecuteResponse.result:type_name -> sekizui.v1.CommandResult
	24, // 2: sekizui.v1.QueryRequest.args:type_name -> google.protobuf.Struct
	25, // 3: sekizui.v1.QueryResponse.status:type_name -> sekizui.v1.Status
	24, // 4: sekizui.v1.QueryResponse.rows:type_name -> google.protobuf.Struct
	26, // 5: sekizui.v1.QueryResponse.refused_by:type_name -> sekizui.v1.RefusedBy
	27, // 6: sekizui.v1.QueryResponse.seiren:type_name -> sekizui.v1.Seiren
	28, // 7: sekizui.v1.SubscribeResponse.envelope:type_name -> sekizui.v1.Envelope
	29, // 8: sekizui.v1.DescribeResponse.capabilities:type_name -> sekizui.v1.Capability
	21, // 9: sekizui.v1.DescribeResponse.payload_schemas:type_name -> sekizui.v1.DescribeResponse.PayloadSchemasEntry
	12, // 10: sekizui.v1.DescribeResponse.available_lenses:type_name -> sekizui.v1.LensInfo
	12, // 11: sekizui.v1.DescribeResponse.imposed_lenses:type_name -> sekizui.v1.LensInfo
	11, // 12: sekizui.v1.DescribeResponse.withheld:type_name -> sekizui.v1.WithheldCapability
	10, // 13: sekizui.v1.DescribeResponse.imposed_refinements:type_name -> sekizui.v1.ImposedRefinement
	22, // 14: sekizui.v1.StartJobRequest.command:type_name -> sekizui.v1.Command
	25, // 15: sekizui.v1.StartJobResponse.status:type_name -> sekizui.v1.Status
	26, // 16: sekizui.v1.StartJobResponse.refused_by:type_name -> sekizui.v1.RefusedBy
	28, // 17: sekizui.v1.JobResultsResponse.envelope:type_name -> sekizui.v1.Envelope
	0,  // 18: sekizui.v1.JobStatusResponse.state:type_name -> sekizui.v1.JobState
	1,  // 19: sekizui.v1.CancelJobRequest.scope:type_name -> sekizui.v1.CancelScope
	2,  // 20: sekizui.v1.GatewayService.Execute:input_type -> sekizui.v1.ExecuteRequest
	4,  // 21: sekizui.v1.GatewayService.Query:input_type -> sekizui.v1.QueryRequest
	6,  // 22: sekizui.v1.GatewayService.Subscribe:input_type -> sekizui.v1.SubscribeRequest
	13, // 23: sekizui.v1.GatewayService.StartJob:input_type -> sekizui.v1.StartJobRequest
	19, // 24: sekizui.v1.GatewayService.CancelJob:input_type -> sekizui.v1.CancelJobRequest
	15, // 25: sekizui.v1.GatewayService.JobStatus:input_type -> sekizui.v1.JobStatusRequest
	16, // 26: sekizui.v1.GatewayService.JobResults:input_type -> sekizui.v1.JobResultsRequest
	8,  // 27: sekizui.v1.GatewayService.Describe:input_type -> sekizui.v1.DescribeRequest
	3,  // 28: sekizui.v1.GatewayService.Execute:output_type -> sekizui.v1.ExecuteResponse
	5,  // 29: sekizui.v1.GatewayService.Query:output_type -> sekizui.v1.QueryResponse
	7,  // 30: sekizui.v1.GatewayService.Subscribe:output_type -> sekizui.v1.SubscribeResponse
	14, // 31: sekizui.v1.GatewayService.StartJob:output_type -> sekizui.v1.StartJobResponse
	20, // 32: sekizui.v1.GatewayService.CancelJob:output_type -> sekizui.v1.CancelJobResponse
	18, // 33: sekizui.v1.GatewayService.JobStatus:output_type -> sekizui.v1.JobStatusResponse
	17, // 34: sekizui.v1.GatewayService.JobResults:output_type -> sekizui.v1.JobResultsResponse
	9,  // 35: sekizui.v1.GatewayService.Describe:output_type -> sekizui.v1.DescribeResponse
	28, // [28:36] is the sub-list for method output_type
	20, // [20:28] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_sekizui_v1_service_proto_init() }
func file_sekizui_v1_service_proto_init() {
	if File_sekizui_v1_service_proto != nil {
		return
	}
	file_sekizui_v1_command_proto_init()
	file_sekizui_v1_core_proto_init()
	file_sekizui_v1_decision_proto_init()
	file_sekizui_v1_envelope_proto_init()
	file_sekizui_v1_seiren_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sekizui_v1_service_proto_rawDesc), len(file_sekizui_v1_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sekizui_v1_service_proto_goTypes,
		DependencyIndexes: file_sekizui_v1_service_proto_depIdxs,
		EnumInfos:         file_sekizui_v1_service_proto_enumTypes,
		MessageInfos:      file_sekizui_v1_service_proto_msgTypes,
	}.Build()
	File_sekizui_v1_service_proto = out.File
	file_sekizui_v1_service_proto_goTypes = nil
	file_sekizui_v1_service_proto_depIdxs = nil
}
